### ISSUE TITLE
Error with local Python SDK Install.

### ISSUE THREAD

**Issue by tylercmsft** [Azure/MachineLearningNotebooks#1216] opened 2020-10-30 21:14 UTC
Hello - I've setup a new environment in my local Anaconda environment (Python 3.).  From the terminal, I issue pip install azureml-sdk.  I receive an error - 
azure-cli-core 2.8.0 requires msal~=1.0.0, but you'll have msal 1.5.1 which is incompatible.
azure-cli-core 2.8.0 requires msal-extensions~=0.1.3, but you'll have msal-extensions 0.2.2 which is incompatible.

Not being sure if this is a benign error, I try to import azureml.core from a notebook, and receive the following error - 
No module named 'azure.mgmt.storage'

Is there any easy workaround for this issue?

**Comment by lostmygithubaccount** [comment] 2020-10-31 01:47
duplicate of #1215, closing

**Closed by lostmygithubaccount** 2020-10-31 01:47 UTC
Labels: duplicate
