### ISSUE TITLE
Notebook not finding directory or file in data folder

### ISSUE THREAD

**Issue by JalalKHZ** [Azure/MachineLearningNotebooks#1598] opened 2021-09-25 13:40 UTC
I have an Excel dataset stored in a data folder which is in the same directory as my notebook. When I try to read the Excel file, I get a FileNotFoundError and that the directory/file does not exist when it clearly does. It was working fine yesterday and I could read any file in the data folder using pandas. 

I check the working directory (os.getcwd()) and it pointed to the compute instance shared folder, and when I tried to change is to the directory (os.chdir()) the notebook is in (Users/firstname.lastname/folder/folder), it gave me the same error. 

What could be the issue here? I had no problem with it before today, and I didn't change anything..

**Comment by diondrapeck** [comment] 2021-09-27 04:55
Hi @JalalKHZ - are you working in a Compute Instance or is this a local setup?

**Comment by JalalKHZ** [comment] 2021-09-27 06:35
A compute instance. To make it work, I had to include the full path, so the path of the compute + /Users/username/folder/data. I didn't need to do that before. I thought it was a pandas issues but I got the same error when I tried to read a file from pickle, etc.

**Comment by diondrapeck** [comment] 2021-09-27 15:15
Thank you for clarifying. I will discuss with Compute Instance team and get back to you.

**Comment by nibirsharif** [comment] 2021-09-27 17:52
I am facing the same issue while creating environment object Environment.from_conda_specification(name, file_path) or InferenceConfig(entry_script='score.py', environment=environment). Last week it was working fine and today got this exception. As mentioned by JalalKHZ, it works when provided directory path and filename ('./code/Users/username/filename').

**Comment by diondrapeck** [comment] 2021-09-28 18:21
@nibirsharif - was this also while using a Compute Instance?

**Comment by diondrapeck** [comment] 2021-09-28 18:31
@JalalKHZ - Compute Instance team pushed a fix yesterday. Could you please try again with relative path and see if it works?

**Comment by JalalKHZ** [comment] 2021-09-28 19:10
@diondrapeck yes, it works now with a relative path. Thank you for the quick fix.

**Comment by diondrapeck** [comment] 2021-09-28 20:06
@JalalKHZ - glad to hear it! @nibirsharif - could you please confirm that the issue is resolved for you as well?

**Comment by nibirsharif** [comment] 2021-09-28 21:08
Thanks @diondrapeck. I'm using compute instance. It's working now :)

**Comment by diondrapeck** [comment] 2021-09-28 22:29
@nibirsharif @JalalKHZ Great - I'm happy the issue is resolved for both of you and thank you for the quick responses!

**Comment by diondrapeck** [comment] 2021-09-28 22:31
@ynpandey - could you please close this issue?

**Closed** 2021-09-28 22:31 UTC
