### ISSUE TITLE
AutoMLStep: cv_split_column_names causes ValueError

### ISSUE THREAD

**Issue by epa095** [Azure/MachineLearningNotebooks#1415] opened 2021-04-03 16:03 UTC
I am trying to use cv_split_column_names  to provide custom CV-splits, but no matter how I specify the column I get a ValueError in the AutoML step. I have a dataprep step which dumps my training data as a **parquet** file with `pandas.to_parquet`. I use `    prepped_data = prepped_data_path.read_parquet_files()`, and my AutoMLConfig is as follows
```
  automl_config = AutoMLConfig(
        task="regression",
...
        training_data=prepped_data,
        label_column_name="y",
        cv_split_column_names=["cva", "cvb"],
    )
```
I have also tried to use indexes, like `cv_split_column_names=[249, 250],` The columns of my dataset is as follows (printed right before written to parquet): `col0 col1 col2 col3 col4 col5  ... col245 col246 col247 y cva cvb`. 

In "70_driver_log" I see the following exception:
```
2021-04-03 15:57:53.753 - INFO - Validating training data.
2021-04-03 15:57:53.754 - INFO - Start data validation.
2021-04-03 15:58:45.676 - INFO - Input data successfully validated.
2021-04-03 15:58:45.677 - INFO - AutoML setup phase for run be776239-2150-432e-9dbe-79ad14eb4506_setup.
2021-04-03 15:58:45.689 - INFO - Checking if feature sweeping is necessary.
2021-04-03 15:58:45.690 - ERROR - AutoML setup script terminated with an exception of type: <class 'ValueError'>
2021-04-03 15:58:45.690 - ERROR - Marking Run be776239-2150-432e-9dbe-79ad14eb4506_setup as Failed.
2021-04-03 15:58:45.692 - CRITICAL - Type: Unclassified
Class: ValueError
Message: Unsupported value for column selection.
Traceback:
  File "setup_run.py", line 74, in execute
    verifier=verifier
  File "experiment_preparation_phase.py", line 59, in run
    DataContextParams(automl_settings))
  File "utilities.py", line 49, in build_raw_data_context
    validation_data=raw_experiment_data.validation_data)
  File "data_context.py", line 201, in __init__
    X = training_data.drop_columns(training_columns_to_drop)
  File "dataflow.py", line 3041, in drop_columns
    'columns': column_selection_to_selector_value(columns)
  File "step.py", line 83, in column_selection_to_selector_value
    if not all(isinstance(column_selection, str) for column_selection in selection): raise ValueError('Unsupported value for column selection.')

```

The pipeline works without `cv_split_column_names `, thats why I think it is the issue.

Versions used (but a bit unsure if that is relevant for the AutoML step):
azureml-sdk==1.25.0
azureml-automl-core==1.25.0.post1
azureml-core==1.25.0
azureml-dataprep==2.11.2

**edit 1**:
It now seems like the size of the dataset *might* affect it. When I use a smaller version of it with roughly 400 000 rows then it works! But when I use a larger version with 1258800 rows then I get the error. Maybe there is some magic aroun 1000000? I will investigate! 

**edit 2**: New  investigations indicate that size matters, but it does not seem to be a clear-cut limit. I have tried to limit my dataset to different lenghts, and as follows is the overview of what sizes causes it to fail (No) and pass (Yes). 
```
[500001 rows x 194 columns]: No
[478143 rows x 194 columns]: No
[478143 rows x 194 columns] :Yes 
[450000 rows x 194 columns]: No
[400000 rows x 194 columns] :No
[350000 rows x 194 columns] :Yes
[300000 rows x 194 columns]: Yes
```
There are some shuffeling involved, so the smaller datasets are not nescesarily subsets of the larger. I will pause investigation a bit until I get feedback from you on where it makes sense to progress.

**Comment by CESARDELATORRE** [comment] 2021-04-05 18:56
@epa095 Can you confirm if you get the same issue if using a plain AutoMLConfig run (instead of using AutoMLStep within an AML Pipeline).

I'd like to isolate if the issue is related to AutoMLStep in piepelines or if the issue always happens to you when using "cv_split_column_names" and that particular data.

Also, can you provide the RUN ID of the AutoMLStep run when the issue happened? Plus the whole log file.

Thanks,

**Comment by epa095** [comment] 2021-04-07 10:53
@CESARDELATORRE Thanks, I sendt an email. The issue persists with a plain AutoMLConfig run.

**Comment by CESARDELATORRE** [comment] 2021-04-07 22:52
Following up in GitHub in case any other user gets to a similar issue. We're in parallel following up with Erik. 
Thanks @epa095 for senfing log files and details. 

We have identified the issue/bug and the team is working on fixing it.
We have created a PR to fix/avoid the issue (_Disable streaming when cv_split_column_names is specified_).

In the meantime, and until the fix is released, you could block the algorithms that cause this conflict (algos using data read streaming) by using the “`blocked_models`” parameter in `AutoMLConfig` class or thru the UI.

**Comment by svaruag** [comment] 2021-04-07 23:02
Hi Erik - Thanks for the detailed description of the problem. You're right in saying that the dataset size matters here, but you're also running into a bug on our side.  

Adding to Cesar's notes above, when we determine that the ratio of dataset size and the available memory on the machine is larger than a particular threshold, we try to avoid scikit-learn algorithms (as they aren't very memory friendly), and instead try to run the model featurization + training in a streaming fashion. The threshold is a bit more nuanced, as it also depends on the type of columns (text, categorical) in addition to the size of the overall dataset. These streaming algorithms currently don't support any form of cross validations. 
The dataset that you're providing with the available memory on the remote machine (where the job is executed) makes this a candidate to run streaming algorithms. However, since you're providing a 'cv_split_column_names' parameter in your settings, that makes it incompatible to run these algorithms, and instead it should be run using the default scikit-learn models. This is a bug on our side, that we'll push out a fix for as soon as in the next release. 

For the time being, you can side-step this bug by blocking the streaming models, which will allow AutoML to recommend scikit-learn models. Please pass in the following to your AutoMLConfig - `blocked_models = ["FastLinearRegressor", "OnlineGradientDescentRegressor"]`

That said, it's likely that you'll be running out of memory given the curent SKU of your remote VM (on which the job is executed) and the dataset characteristics. We recommend chosing a machine with at-least 80GB of memory. A list of available SKUs can be found [here](https://azure.microsoft.com/en-us/pricing/details/machine-learning/).

**Comment by epa095** [comment] 2021-04-09 08:19
Thanks for the quick feedback:-) 

Is it documented somewhere what models gets deactivated with larger training set? If I knew the threashold(s) I would want to try to samle my dataset to the largest size it can be while still having all models tried. But I also understand that documenting this can become a bit of a nightmare if you use complicates rules :-p

Feel free to close this issue, or keep it open if you want it as a way to track progress in your internal task.

**Comment by CESARDELATORRE** [comment] 2021-07-21 17:33
@epa095 Hi Erik. Basically, for very large data, only the models/algorithms that support "data streaming" while training are the ones activated. Those are the following:

Supported learners (Data Streaming) 
•	Regression: 
            - OnlineGradientDescent 
            - FastLinearRegressor 
•	Classification: 
            - AveragedPerceptron 
            - LinearSVM 

These algorithms are NimbusML algorithms which support data streaming while training. 

You can see all the algorithms supported by Azure ML AutoML in this page (Scroll down until you see the "Supported models" section):
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-auto-train#training-validation-and-test-data

About Time Series Forecasting, there are *no* Time Series Forecasting learners in Azure ML AutoML that support data streaming (for large data, meaning much larger than what in-memory fits). 

Closing the issue as per user's comment. 👍

**Closed by CESARDELATORRE** 2021-07-21 17:33 UTC
Labels: ADO, Auto ML, product-question
