### ISSUE TITLE
automl_env.yml is too old

### ISSUE THREAD

**Issue by dem108** [Azure/MachineLearningNotebooks#1147] opened 2020-09-15 16:28 UTC
When I create Conda env with:
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/automl_env.yml
it installs azureml-core==1.1.5.4 which is way too old. According to the release history, it's about 6 months old.
We should update this .yml to allow installing the latest bits.

**Comment by deepakmukunthu** [comment] 2020-09-26 01:26
@jeff-shepherd can you please look into this?

**Comment by jeff-shepherd** [comment] 2020-09-26 02:40
@dem108 I couldn't reproduce the issue.  I downloaded the latest files from this repo and ran the command `automl_setup sdk1.14.0`.  This creates a new environment using automl_env.yml.  I then checked the version with `pip list`.  The output included `azureml-core   1.14.0.post1`, which is the correct version.

Can you check that you are looking at the correct environment?  Sometimes, I install a new environment and then open an existing notebook in `jupyter notebook`.  The existing notebook uses a previous environment rather than the one that I just created.  I then use the **Kernel | Change Kernel** option to select the correct environment.

If that isn't the issue, can you share the output of `conda -V`, the command that you used to create the environment and the command you used to check the version?

**Comment by CESARDELATORRE** [comment] 2020-09-28 21:33
@dem108 Do you have any further input about the proposed actions above?
Thanks,

**Comment by dem108** [comment] 2020-09-29 06:46
When I test with `automl_setup`, it failes when parsing .yml:
```
Solving environment: failed

ResolvePackageNotFound: 
  - numpy~=1.18.0
```
Any tip why this fails?

When I edited it to specify it as `numpy` (no version range), I was able to run it successfully. So for now I think we can close this issue. But I'd appreciate if you look at why `numpy~=1.18.0` (note the ~ sign) fails.

Thanks

**Comment by CESARDELATORRE** [comment] 2020-09-29 20:19
Adding @rtanase so his team looks into the "why numpy~=1.18.0 (note the ~ sign) fails."

Closing this issue, for now, as requested.

#please-close

**Closed by CESARDELATORRE** 2020-09-29 20:19 UTC
Labels: Auto ML

**Comment by rtanase** [comment] 2020-09-29 21:48
@dem108, was the installation done on mini-conda? and if so, what was the version you used?
Was this for a brand new environment, or for an existing one? If it was an existing environment, can you also share the pip list? 
I'm curious about the pip & Python versions.

**Comment by dem108** [comment] 2020-09-30 04:31
@rtanase It happened in my local environment, but I could reproduce it in a new environment in a newly created Compute Instance yesterday. Let me check the details you requested and get back to you.

**Comment by dem108** [comment] 2020-09-30 08:55
@rtanase Does the following help?

```
$ cat simple_env.yml 
name: simple
dependencies:
- numpy~=1.16.0

- pip:

$ conda env create -f simple_env.yml 
Solving environment: failed

ResolvePackageNotFound: 
  - numpy~=1.16.0

$ pip --version
pip 20.1.1 from /anaconda/envs/azureml_py36/lib/python3.6/site-packages/pip (python 3.6)

$ python --version
Python 3.6.9 :: Anaconda, Inc.
```

**Comment by jeff-shepherd** [comment] 2020-10-02 00:54
@dem108 Thanks for the additional information.

I found that this issue is cause by the Conda version being older than 4.7.8.

Automl packages are already installed in the azureml_py36 environment in Compute Instances.  So, you don't need to run automl_setup_linux.sh on Compute Instance.

To setup another environment, please run the command “conda update conda” first to update Conda.

I am updating the automl_setup scripts to check the conda version and give a better error message.
