### ISSUE TITLE
Need to add description for each transformer in this page. 

### ISSUE THREAD

**Issue by CESARDELATORRE** [Azure/MachineLearningNotebooks#914] opened 2020-04-12 21:34 UTC
There's no a single explanation/description in this page. Each transformer should have a short description saying what it does. i.e. "What MaxAbsScaler does".

This other page has the same issue:
https://docs.microsoft.com/en-us/python/api/azureml-automl-core/azureml.automl.core.constants.supportedtransformersfactorynames.generic?view=azure-ml-py#maxabsscaler

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 013da6d7-0ade-fbec-ca99-51fb480ccf34
* Version Independent ID: 52769d53-d284-3a25-99c8-c11d00707011
* Content: [azureml.automl.core.constants.SupportedTransformers class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-automl-core/azureml.automl.core.constants.supportedtransformers?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-automl-core/azureml.automl.core.constants.SupportedTransformers.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-automl-core/azureml.automl.core.constants.SupportedTransformers.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by ram-msft** [comment] 2020-04-13 01:29
@CESARDELATORRE Thanks for the feedback. duplicate of https://github.com/Azure/MachineLearningNotebooks/issues/913.
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Closed by ram-msft** 2020-04-13 01:29 UTC
Labels: automl, cxp, doc-bug, triaged
