### ISSUE TITLE
Panda errors: Typically seen during AutoML Experiment:

### ISSUE THREAD

**Issue by munyamunya** [Azure/MachineLearningNotebooks#1372] opened 2021-02-26 10:39 UTC
>Panda errors: Typically seen during AutoML Experiment:
Pandas errors ?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8e0e12a4-b363-2726-06b4-9db2015efb32
* Version Independent ID: e39a91ac-375b-a2cc-350d-a82cb7b0b035
* Content: [Azure Machine Learning SDK for Python をインストールする - Azure Machine Learning Python](https://docs.microsoft.com/ja-jp/python/api/overview/azure/ml/install?view=azure-ml-py)
* Content Source: [AzureML-Docset/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/MachineLearning-Python-pr.ja-JP/blob/live/AzureML-Docset/docs-ref-conceptual/install.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @harneetvirk
* Microsoft Alias: **harnvir**

**Comment by lostmygithubaccount** [comment] 2021-02-26 15:21
hi @munyamunya we are going to need more information to properly address this issue

**Comment by munyamunya** [comment] 2021-02-26 15:50
hello

I saw this problem here.
https://docs.microsoft.com/ja-jp/python/api/overview/azure/ml/install?view=azure-ml-py

**Comment by lostmygithubaccount** [comment] 2021-03-01 04:35
@munyamunya can you expand on what the issue is? 

The initial issue refers to "Pandas errors ?", and your response points to the Japanese version of the SDK article - is this something specific to the Japanese translation of the article? Or a different issue? 

Without more information there is not much we can do to address this issue.

**Comment by munyamunya** [comment] 2021-03-01 05:12
Hello.

Could you refer to the following information ?

English site

https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py

Panda errors: Typically seen during AutoML Experiment:

When manually setting up your environment using pip, you may notice
attribute errors (especially from pandas) due to unsupported package
versions being installed. In order to prevent such errors, please install
the AutoML SDK using the automl_setup.cmd
<https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/README.md>
:

   1. Open an Anaconda prompt and clone the GitHub repository for a set of
   sample notebooks.

**Comment by CESARDELATORRE** [comment] 2021-03-15 18:38
@munyamunya Can you confirm that your ask is for the AML docs to be explicit on examples for what particular errors the [doc](https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py) is talking about when it says:
_"you may notice attribute errors (especially from pandas) due to unsupported package versions being installed."_

Is your ask to mention a few examples of those "attribute errors"?
Or do you have any other ask?

Thanks,

**Comment by CESARDELATORRE** [comment] 2021-04-07 00:45
This is already fixed saying sample errors explicitly in the documentation:

https://docs.microsoft.com/en-us/python/api/overview/azure/ml/install?view=azure-ml-py

_Panda errors: Typically seen during AutoML Experiment:

When manually setting up your environment using pip, you may notice errors (especially from pandas) due to unsupported package versions being installed.

For example, ModuleNotFoundError: No module named 'pandas.core.internals.managers'; 'pandas.core.internals' is not a package

In order to prevent such errors, please install the AutoML SDK using the automl_setup.cmd:_

Closing the issue.

**Closed by CESARDELATORRE** 2021-04-07 00:45 UTC
Labels: Auto ML, question
