### ISSUE TITLE
 NotImplementedError: Child run is unsupported for Pipeline run.

### ISSUE THREAD

**Issue by ashoksamal6363** [Azure/MachineLearningNotebooks#443] opened 2019-06-22 18:43 UTC
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
&lt;ipython-input-50-2f6094393b0c&gt; in &lt;module&gt;
----&gt; 1 pipeline_run.child_run()

~/anaconda3_501/lib/python3.6/site-packages/azureml/pipeline/core/run.py in child_run(self, name, run_id, outputs)
    102         :rtype: azureml.core.run.Run
    103         """
--&gt; 104         raise NotImplementedError("Child run is unsupported for Pipeline run.")
    105 
    106     #######################################

NotImplementedError: Child run is unsupported for Pipeline run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1f08c12-3482-3ca6-d593-6237fdc60ff1
* Version Independent ID: d4cbab76-400b-8c64-1583-40a74de14e87
* Content: [azureml.pipeline.core.PipelineRun class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.pipelinerun?view=azure-ml-py#feedback)
* Content Source: [AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineRun.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-pipeline-core/azureml.pipeline.core.PipelineRun.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by danielsc** [comment] 2019-07-10 17:02
Duplicate of #324

**Closed by danielsc** 2019-07-10 17:02 UTC
