### ISSUE TITLE
Local env requirements to submit AutoML jobs to AMLCompute

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#925] opened 2020-04-15 18:44 UTC
what packages do i need to install on my local env to submit AutoML jobs to AMLCompute? i thought that it was sufficient to use `pip install azureml-sdk` and that `pip install azureml-sdk[automl]` was only needed if you want to have the automl runs happen in AMLCompute.
@jadhosn @CESARDELATORRE @Aniththa @nibaccam

I have a new environment with SDK version 1.3.0. here's the azureml libraries in my environment
```
azureml-automl-core                  1.3.0
azureml-contrib-notebook             1.3.0
azureml-core                         1.3.0
azureml-dataprep                     1.4.3
azureml-dataprep-native              14.1.0
azureml-interpret                    1.3.0
azureml-pipeline                     1.3.0
azureml-pipeline-core                1.3.0
azureml-pipeline-steps               1.3.0
azureml-sdk                          1.3.0
azureml-telemetry                    1.3.0
azureml-train                        1.3.0
azureml-train-automl-client          1.3.0
azureml-train-core                   1.3.0
azureml-train-restclients-hyperdrive 1.3.0
azureml-widgets                      1.3.0
```

When I try and submit a job, I'm getting this error
```python
compute_target = pf.get_or_create_compute(workspace=ws,
                                          compute_target_name=compute_target_name,
                                          vm_size='STANDARD_D12_V2',
                                          max_nodes=100,
                                          idle_seconds_before_scaledown=1800
                                          )

settings = {
    "automl_generic": {
        'task':'forecasting',
        'primary_metric':'normalized_root_mean_squared_error',
        'enable_ensembling':False,
        'verbosity':logging.INFO,
        'compute_target':compute_target,
        'max_concurrent_iterations':4,
        'max_cores_per_iteration':1,
        'experiment_timeout_minutes':15,
        
    },
    "time_series" : {
        "time_column_name": 'Month',
        "grain_column_names": "CountryNm",
        "max_horizon": 18,
        "target_lags": [12,24],
        "target_rolling_window_size": "auto"
    },
    "data" : {
        "label_column_name":'HPE',
        "training_data":train,
        "validation_data":valid,
        "n_cross_validations":5
    }

    
}

automl_config = AutoMLConfig(
    **settings['automl_generic'],
    **settings['time_series'],
    **settings['data']

)
run = exp.submit(automl_config, show_output=True)
```

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-62-7c2851ee04b2> in <module>
----> 1 local_run = exp.submit(automl_config, show_output=True)

~\AppData\Local\Continuum\miniconda3\lib\site-packages\azureml\core\experiment.py in submit(self, config, tags, **kwargs)
    200         submit_func = get_experiment_submit(config)
    201         with self._log_context("submit config {}".format(config.__class__.__name__)):
--> 202             run = submit_func(config, self.workspace, self.name, **kwargs)
    203         if tags is not None:
    204             run.set_tags(tags)

~\AppData\Local\Continuum\miniconda3\lib\site-packages\azureml\train\automl\automlconfig.py in _automl_static_submit(automl_config_object, workspace, experiment_name, **kwargs)
     79     if in_process is True:
     80         try:
---> 81             import azureml.train.automl.runtime
     82             automl_run = _default_execution(experiment, settings, fit_params, show_output)
     83         except ImportError as e:

~\AppData\Local\Continuum\miniconda3\lib\site-packages\azureml\train\automl\runtime\__init__.py in <module>
     21     # Suppress the warnings at the import phase.
     22     warnings.simplefilter("ignore")
---> 23     from .automl_step import AutoMLStep, AutoMLStepRun
     24 
     25 __all__ = [

~\AppData\Local\Continuum\miniconda3\lib\site-packages\azureml\train\automl\runtime\automl_step.py in <module>
     25 from azureml.train.automl.automlconfig import AutoMLConfig
     26 from azureml.train.automl.exceptions import ConfigException
---> 27 from .run import AutoMLRun
     28 
     29 

~\AppData\Local\Continuum\miniconda3\lib\site-packages\azureml\train\automl\runtime\run.py in <module>
     11 import numpy as np
     12 import pandas as pd
---> 13 from azureml.automl.runtime.data_context import TransformedDataContext
     14 from azureml._restclient.constants import RunStatus
     15 from azureml.train.automl.run import AutoMLRun as _AutoMLRun

~\AppData\Local\Continuum\miniconda3\lib\site-packages\azureml\automl\runtime\data_context.py in <module>
     14 from automl.client.core.common.dataflow_utilities import PickleableDataflow
     15 from automl.client.core.common.utilities import _get_ts_params_dict
---> 16 from automl.client.core.runtime import memory_utilities
     17 from automl.client.core.runtime._cv_splits import _CVSplits
     18 from automl.client.core.runtime.cache_store import MemoryCacheStore

ModuleNotFoundError: No module named 'automl.client.core.runtime'
```

**Comment by CESARDELATORRE** [comment] 2020-04-15 19:29
With the packages listed here should be enough:
https://github.com/Azure/MachineLearningNotebooks/blob/master/NBSETUP.md

Plus also the following for Widgets in notebooks.

I think I use the following for my PC Conda environment and optionally the other packages in the URL above:

pip install azureml-sdk[notebooks,automl]

pip install azureml-sdk[explain,contrib]

pip install azureml-widgets

**Comment by swanderz** [comment] 2020-04-15 19:40
So there may be a weird environment issue (or an SDK bug) going on, but my question is really about what I read in the [release notes for 1.0.76](https://docs.microsoft.com/en-us/azure/machine-learning/azure-machine-learning-release-notes#azure-machine-learning-sdk-for-python-v1076)

> azureml-train-automl-client
> Added a thin client for submitting AutoML experiments without needing to install any machine learning dependencies locally.

I'd like to avoid the `automl` option if possible

**Comment by nibaccam** [comment] 2020-04-29 17:34
@Aniththa @CESARDELATORRE  can you help here, please?

**Comment by CESARDELATORRE** [comment] 2020-04-30 03:45
@rtanase (Razvan) Can you explain here the minimum packages to install when using remote AML compute runs? (azureml-train-automl-client), so you are not really training on your local environment.

I think that's your scenario, right?

**Comment by SKrupa** [comment] 2020-05-01 17:31
Hi @swanderz it looks like the issue is not related to packaging, but rather its trying to run a local run instead of a remote run, a local run requires all the packages to be available locally for training, (so azureml-train-automl-runtime would need to be installed.) Do you have both a local and remote scenario in your notebook? In the sample code I see 

run = exp.submit(automl_config, show_output=True)

which passes a compute_target, which should be working, but in the stack trace I see 

<ipython-input-62-7c2851ee04b2> in <module>
----> 1 **local_run** = exp.submit(automl_config, show_output=True)

which implies its trying to submit a local run. Going through the stack trace shows its hitting our local code path as well, which is why it throws this package error.

**Comment by swanderz** [comment] 2020-05-01 19:59
@SKrupa I appreciate your careful reading. I was using the variable `local_run`, but deciding to rename it to `run` for the purpose of this GitHub issue. But I forgot to change it in the stacktrace. 

@CESARDELATORRE, can your team reproduce the behavior on your end?
cc: @jadhosn

**Comment by SKrupa** [comment] 2020-05-04 22:01
@swanderz There's a couple things that seem to be going on here:
1) It seems like your local environment has some old versions of the SDK. Specifically, its running an old version of "azureml-train-automl-runtime" and "azureml-automl-runtime" packages, which suspiciously don't show up in your pip list. From the file path "AppData\Local\Continuum\miniconda3\lib\site-packages\" it seems like you probably have something installed in your base environment. I'd recommend running "pip uninstall azureml-train-automl-runtime" and "pip uninstall azureml-automl-runtime" in the base env.

2) We're hitting the local code path, which happens if compute_target is None or empty string. What is "pf.get_or_create_compute"? I'm not aware of an API we expose like this. Could you add a check to verify that the return from this is not None? And if it isn't can you also check compute_target.name is valid and compute_target.provisioning_state is "Succeeded"?

If compute_target is not None and has a valid name and provisioning state, would you be able to provide more details about this compute? That would help us hopefully get a repro of the issue.

Thanks!

**Comment by swanderz** [comment] 2020-05-05 21:45
@SKrupa thanks for sticking with me here. I _did_ have a conda issue and completely wiped it. My mistake was adding conda dirs to the the PATH variable. It caused the base environment's `pip` to be used regardless of what environment I was in... /facepalm.

So now I've got a fresh environemnt with the following azureml packages:
```bash
(azureml_test) C:\Users\anders.swanson\Documents\MachineLearningNotebooks>where pip
C:\Users\anders.swanson\Anaconda3\envs\azureml_test\Scripts\pip.exe

(azureml_test) C:\Users\anders.swanson\Documents\MachineLearningNotebooks>pip list | grep "azureml"
azureml-automl-core                  1.4.0
azureml-contrib-notebook             1.4.0
azureml-core                         1.4.0.post2
azureml-dataprep                     1.4.6
azureml-dataprep-native              14.1.0
azureml-pipeline                     1.4.0
azureml-pipeline-core                1.4.0
azureml-pipeline-steps               1.4.0
azureml-sdk                          1.4.0
azureml-telemetry                    1.4.0
azureml-train                        1.4.0
azureml-train-automl-client          1.4.0
azureml-train-core                   1.4.0
azureml-train-restclients-hyperdrive 1.4.0
azureml-widgets                      1.4.0
```

I was able to submit the [`forecasting-beer-remote.ipynb`](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/forecasting-beer-remote/auto-ml-forecasting-beer-remote.ipynb) with the above environment (i.e. w/o the full `automl` package set).

However, I was only able to do so by overriding `AutoMLConfig`'s  `model_explainability` param from its default value of `True` to `False`. Before I did that, I got this error:
`"Please install azureml-explain-model package for model explanations"`. ([full stack trace](https://gist.github.com/swanderz/6c59971fc81f9efe012db42c5b9ac87c))

Is it really necessary that `azureml-explain-model` be installed locally in order to get explanations remotely?

**Comment by SKrupa** [comment] 2020-05-05 23:03
@swanderz Cool! Glad to hear it was just an issue with the base env, I've run into similar issues on my own machine so figured I'd make sure :).

As for azureml-explain-model needing to be installed, that seems to be a bug on our side. I've created an item for our team and this will be addressed in a future release. In the meantime, the only work arounds would be to either install "azureml-explain-model" locally or to disable to feature entirely.

**Comment by nibaccam** [comment] 2020-05-06 19:20
@swanderz thank you for reporting this. I've created an internal doc team work item to document the work around. @SKrupa I'll tag you in the item so we can coordinate. We will now proceed to close this thread. #please-close

**Closed** 2020-05-06 19:41 UTC
Labels: Auto ML, cxp, product-question, triaged
