### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by antti-saarela** [Azure/MachineLearningNotebooks#766] opened 2020-02-06 11:49 UTC
This page contains broken links. For example https://aka.ms/tabulardataset-samplenotebook leads to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b658a7-cc75-5dc6-cc09-47a286e2f49d
* Version Independent ID: 5244c83f-144a-d17e-a34d-d536b78f60e1
* Content: [azureml.data package - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by vmagelo** [comment] 2020-02-19 19:05
I'm not able to reproduce.  Maybe momentary glitch? Connectivity issue? Here's what I see (and have seen for a few months now):

![image](https://user-images.githubusercontent.com/51368918/74866460-308a9180-5353-11ea-8485-434f8511b671.png)

**Comment by j-martens** [comment] 2020-02-19 21:37
Thanks for your report. Looks fixed now.

**Closed by j-martens** 2020-02-19 21:37 UTC
