### ISSUE TITLE
Re-registering a dataset does not create new version

### ISSUE THREAD

**Issue by stemoor** [Azure/MachineLearningNotebooks#885] opened 2020-03-24 21:32 UTC
When trying to register a dataset with the flag create_new_version=True, I get an error instead of creating a new version. 

I get the following error: 
```python 
  File "register.py", line 110, in register_dataset
    ds.register(workspace, name=name, create_new_version=True)
  File "/data/anaconda/envs/cyril/lib/python3.6/site-packages/azureml/data/_loggerfactory.py", line 106, in wrapper
    return func(*args, **kwargs)
  File "/data/anaconda/envs/cyril/lib/python3.6/site-packages/azureml/data/abstract_dataset.py", line 313, in register
    raise result
Exception: An identical dataset had already been registered, which can be retrieved with `Dataset.get_by_name(workspace, name="cases_train_data.csv", version=1)`.
```

Here is my call to register the data set:

```python
    ds = Dataset.Tabular.from_delimited_files(path)
    ds.register(workspace, name=name, create_new_version=True)
```

SDK Version: azureml-sdk==1.2.0

**Comment by GiftA-MSFT** [comment] 2020-03-25 01:14
@stemoor we will review your feedback and get back to you shortly. Thanks.

**Comment by RSavage2** [comment] 2020-03-25 17:01
Thanks for reaching out to us. We are investigating the case. Will reach back if we need more info.

**Comment by MayMSFT** [comment] 2020-03-25 18:15
@stemoor  
re-regitering the same data (datastore+path) with the same workspace is not supported at the moment. Looks like you have already registered the same data under (name="cases_train_data.csv", version=1). If you want to register this data under a different name, you need to first unregister dataset "cases_train_data.csv".

We are adding support ot enable users registering the same data under different names. We will add this in our release notes once the feature is in.

Thanks!

**Comment by GiftA-MSFT** [comment] 2020-03-26 02:53
Thanks for the updates @MayMSFT .

@stemoor we will now proceed to close this thread. Thanks.

**Comment by stemoor** [comment] 2020-03-26 21:50
Okay, so if I want to update the data how does that work? If I update the data on the datastore, does the update get reflected on the dataset? Or, every time I update the data on the datastore, do I have to unregister it and then re-register it? My data is always updating, so I need to know what it the proper way to handle this case.

**Comment by GiftA-MSFT** [comment] 2020-03-26 22:43
Please check out [dataset versioning](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-version-track-datasets) which may be applicable to your scenario. You can specify 'create_new_version = True' when registering a new version. Hope this helps. Thanks.

**Comment by stemoor** [comment] 2020-03-26 23:16
Your suggestion is exactly what I tried doing that got me the error above. I tried registering under the same name using the flag 'create_new_version = True' and got the error above.

**Comment by GiftA-MSFT** [comment] 2020-03-27 00:01
@stemoor apologies. I will reopen this thread.
@MayMSFT the [document](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-version-track-datasets#register-and-retrieve-dataset-versions) states that 'You can register multiple datasets under the same name and retrieve a specific version by name and version number.' Can you help clarify?

**Comment by stemoor** [comment] 2020-03-27 00:27
Nevermind! I am sorry I thought I was registering the same data set under the same name but I was wrong by a single letter. Sorry! This is all resolved! Thanks for all your time!

**Comment by jmwoloso** [comment] 2021-01-13 00:35
Version incrementing happens, however, amls seems to simply append the new data to the existing previous versions which seems like a bug.

**Comment by lostmygithubaccount** [comment] 2021-02-19 13:20
any updates on this?

**Comment by ganzhi** [comment] 2021-04-23 21:42
@jmwoloso, can help share how you register both version of datasets? By design, new version of dataset is completely independent of old version of dataset.

**Comment by jmwoloso** [comment] 2021-04-23 22:35
@ganzhi right now the only thing that works is to use `Dataset.get_by_name(...).unregister_all_versions()` and then we register a new version after that.

**Comment by ganzhi** [comment] 2021-04-23 22:41
@jmwoloso, is there a way that I can reproduce your issue? I can't produce it locally. Thanks!

**Comment by rfarmaha** [comment] 2021-04-27 20:29
@jmwoloso I wasn't able to repro this issue either. Could you provide a sample code snippet, along with the SDK version that you're running?

**Comment by ynpandey** [comment] 2021-05-20 19:36
@stemoor Can you please try the workflow with the latest version of SDK and check if you still see this behavior. If you still see this behavior, please reopen this issue.

**Closed** 2021-05-20 20:45 UTC
Labels: ADO, Data4ML, bug

**Comment by hemanshug** [comment] 2022-08-15 13:41
Hi all, the dataset version refers to single source of truth, if your dataset version refers to same files (in case of table dataset or folders in case of file dataset), you will not see the change in version although you could have changed files. New version registers only if you specify new folder or new files. Hope that helps.

**Comment by gyasibaaye** [comment] 2023-05-05 21:59
Has this been resolved? I am running into the same issue right now running the following command

`ds = ds.register(workspace = ws, name = 'test', create_new_version=True)`

**Comment by jmwoloso** [comment] 2023-05-05 22:21
@gyasibaaye we're currently using 1.39.0 of the sdk and `create_new_version` is "working". I say "working" because it ticks the version, but the `Dataset` doesn't keep a copy of your data anywhere. 

The dataset is just a pointer to the actual location where you are storing the input to the Dataset. We're re-evaluating even using datasets at all because of this. We discovered that it wasn't actually storing a copy anywhere when we attempted to pull prior versions of a dataset and the data ended up being identical to the current registered version. 

The Dataset functionality is pointless, at least in this version of the sdk. Upgrading is incredibly painful because there are about 1000 dependency packages this library relies on and they break our existing environment dependencies because they're all pinned to out of date versions of packages that we depend on.

**Comment by gyasibaaye** [comment] 2023-05-08 14:08
@jmwoloso Thank you for the prompt reply! I am running  so to make sure I understand you correctly I have four follow up questions. 
* I am running 1.48.0 of azureml-core, is that functionally different than the azureml-sdk?
* If I want to register a folder in my datastore as a versioned asset like I was trying above with my test, There is a chance it may not actually version it (i.e. by creating a pointer to the new datastore location)? 
* Furthermore, If I were to create a new version through the UI rather than the Python SDK, would I still face potentially the same issue?
* Lastly, would you recommend simply creating a new asset for the datastore location?
