### ISSUE TITLE
EstimatorStep and Estimator use different classes for script_params and estimator_entry_script_arguments

### ISSUE THREAD

**Issue by sam-harvey** [Azure/MachineLearningNotebooks#968] opened 2020-05-13 08:27 UTC
In Estimator we have

>script_params
>    dict 

> A dictionary of command-line arguments to pass to the training script specified in entry_script.

In EstimatorStep we have

>estimator_entry_script_arguments
>   list[str] 

>[Required] A list of command-line arguments. If the Estimator's entry script does not accept commandline arguments, set this parameter value to an empty list.

Is there a reason why EstimatorStep couldn't accept a dict too? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68a828a8-b656-f952-dbe7-0cba5cbe17ae
* Version Independent ID: 0b40f59c-e9e4-f311-f936-1565684ec01e
* Content: [azureml.pipeline.steps.estimator_step.EstimatorStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-gb/python/api/azureml-pipeline-steps/azureml.pipeline.steps.estimator_step.estimatorstep?view=azure-ml-py#feedback)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.estimator_step.EstimatorStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.estimator_step.EstimatorStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by BharathNimmala-MSFT** [comment] 2020-05-13 23:22
@sam-harvey Thank you for your query, assigned this issue to our document author @j-martens to further look into it.

**Comment by lostmygithubaccount** [comment] 2020-08-27 19:32
I believe this is by design and won't be fixed in v1 of the SDK, but will be addressed in v2 - closing

**Closed by lostmygithubaccount** 2020-08-27 19:32 UTC
Labels: Training, assigned-to-author, doc-enhancement, product-question, triaged
