### ISSUE TITLE
AttributeError: '_AutoMLRegressor' object has no attribute 'logger'

### ISSUE THREAD

**Issue by rquintino** [Azure/MachineLearningNotebooks#31] opened 2018-10-01 11:18 UTC
while running automl on regression problem, for two of the initial models:

ITERATION     PIPELINE                               DURATION                METRIC      BEST
         0      SparseNormalizer ElasticNet           0:00:16.517861           0.149     0.149
         1     
Exception ignored in: <bound method _AutoMLBase.__del__ of <azureml.train.automl._automlregressor._AutoMLRegressor object at 0x7f78d690a860>>
Traceback (most recent call last):
  File "/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azureml/train/automl/_automlbase.py", line 180, in __del__
    if self.logger is not None:
AttributeError: '_AutoMLRegressor' object has no attribute 'logger'
 SparseNormalizer ExtraTreesRegressor  0:00:23.785131           0.150     0.149
         2     

Exception ignored in: <bound method _AutoMLBase.__del__ of <azureml.train.automl._automlregressor._AutoMLRegressor object at 0x7f78d690a860>>
Traceback (most recent call last):
  File "/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azureml/train/automl/_automlbase.py", line 180, in __del__
    if self.logger is not None:
AttributeError: '_AutoMLRegressor' object has no attribute 'logger'

 StandardScalerWrapper DecisionTreeRegr0:00:15.952069           0.159     0.149
         3      PCA ElasticNet                        0:00:16.759112           0.150     0.149

**Comment by chaoqian** [comment] 2018-10-01 17:00
Hi, could you please tell us what version of SDK are you using?

**Comment by rquintino** [comment] 2018-10-01 17:38
From azure notebooks: 

SDK version | 0.1.59

**Comment by chaoqian** [comment] 2018-10-01 18:06
Hi, thanks for your reply.

The exception is because of failures to construct logger inside SDK code, the exception is known and we will fix them in Nov release.  

However, it is interesting that the failures of the logger only happened on part of the iterations that you ran, not all of it. So to help us better dive deep into the issue, do you mind sending us the automl_config settings that you ran? Also could you confirm with us the notebook you tried is "02.auto-ml-regression"?

Thanks,
-Chao

**Comment by skasturi** [comment] 2019-04-01 03:37
@rquintino , This has been fixed in the November release. Please upgrade to the latest version of the SDK and let us know if you still face any issues. 

Thank you for your patience and trying AutoML. 

@rastala, Please close this as this is fixed.

**Closed** 2019-05-21 20:53 UTC
