### ISSUE TITLE
Azure Notebooks with is out of date

### ISSUE THREAD

**Issue by leolorenzoluis** [Azure/MachineLearningNotebooks#457] opened 2019-06-30 05:08 UTC
Following the tutorial how-to-use-azureml/machine-learning-pipelines/nyc-taxi-data-regression-model-building/nyc-taxi-data-regression-model-building.ipynb

Running the following command produces an error
```
from azureml.contrib.opendatasets import NycTlcGreen, NycTlcYellow
import pandas as pd
from datetime import datetime
from dateutil.relativedelta import relativedelta

green_df_raw = pd.DataFrame([])
start = datetime.strptime("1/1/2016","%m/%d/%Y")
end = datetime.strptime("1/31/2016","%m/%d/%Y")

number_of_months = 1
sample_size = 5000

for sample_month in range(number_of_months):
    temp_df_green = NycTlcGreen(start + relativedelta(months=sample_month), end + relativedelta(months=sample_month)) \
        .to_pandas_dataframe()
    green_df_raw = green_df_raw.append(temp_df_green.sample(sample_size))
```
Error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-ae4283ea54b6> in <module>
----> 1 from azureml.contrib.opendatasets import NycTlcGreen, NycTlcYellow
      2 import pandas as pd
      3 from datetime import datetime
      4 from dateutil.relativedelta import relativedelta
      5 

ModuleNotFoundError: No module named 'azureml.contrib.opendatasets'
```

**Comment by davidefiocco** [comment] 2019-07-08 16:33
Just run on your terminal  
`pip install azureml-contrib-opendatasets`
You may want to make sure that the version of that package matches that of `azureml-core`, which you can achieve with:  
`pip install --upgrade azureml-core`
That should solve that `ModuleNotFoundError`.

**Comment by mgolub2** [comment] 2019-12-03 00:29
I believe the issue is that `azureml-contrib-opendatasets` is now deprecated in favor of `azureml-opendatasets`. I resolved this issue by making sure `azureml-contrib-opendatasets` was uninstalled, and installed `azureml-opendatasets` in it's place. Then, `import azureml.opendatasets` should work without issue. 

This can be achieved via:
```bash
pip uninstall azureml-contrib-opendatasets
pip install --upgrade azureml-opendatasets
```

**Comment by v-strudm-msft** [comment] 2020-04-20 23:08
Thank you for your post. It looks as thought this issue was resolved so we will close this thread. Should you have additional questions, please continue to post here and we will gladly continue the discussion.

**Closed by v-strudm-msft** 2020-04-20 23:08 UTC
