### ISSUE TITLE
Keyvault.list_secrets() returns nothing 

### ISSUE THREAD

**Issue by jadhosn** [Azure/MachineLearningNotebooks#586] opened 2019-09-23 21:16 UTC
**Describe the bug**
While using Keyvault from azureml.core.Keyvault, the method list_secrets() does not return anything in the list, knowing that I can access the secrets by name. 

+ Python & SDK version
Python v3.6.2
azureml-sdk v1.0.57

**To Reproduce**
```
from azureml.core.workspace import Workspace
from azureml.core.keyvault import Keyvault

# Get current workspace 
ws = Workspace.from_config()

# Define key vault to set and retrieve secrets from the keyvault
kv = Keyvault(ws)

kv.list_secrets() # returns an empty list

kv.get_secret('jad') # returns value stored in secrets
```

**Comment by jadhosn** [comment] 2019-09-24 00:43
> Steps to reproduce the behavior:
> 
> ```
> from azureml.core.workspace import Workspace
> from azureml.core.keyvault import Keyvault
> 
> # Get current workspace 
> ws = Workspace.from_config()
> 
> # Define key vault to set and retrieve secrets from the keyvault
> kv = Keyvault(ws)
> 
> kv.list_secrets() # returns an empty list
> 
> kv.get_secret('jad') # returns value stored in secrets
> ```

It seems that the function only returns the secrets that were defined from inside the workspace, and not through the azure portal.

**Comment by swanderz** [comment] 2019-10-02 16:11
@jpe316  @rastala can we get someone to repro this? My hopes are crashing

cc: @alieus

**Comment by alieus** [comment] 2019-10-02 17:40
@swanderz @jadhosn  It looks like there is a Key Vault that is implicitly created for you by default along with your ws. This is different from the Key Vault you've created on the portal. 

try:

from azureml.core.workspace import Workspace
from azureml.core.keyvault import Keyvault

# Get current workspace 
ws = Workspace.from_config()

# Define key vault to set and retrieve secrets from the keyvault
kv = Keyvault(ws)
kv.set_secret(name = "jad", value ="test")

print(kv.list_secrets()) # should return [{'name': 'jad'}]

kv.get_secret('jad') # returns value stored in secrets

**Comment by jadhosn** [comment] 2019-10-02 18:26
> @swanderz @jadhosn It looks like there is a Key Vault that is implicitly created for you by default along with your ws. This is different from the Key Vault you've created on the portal.

@alieus so the key-vault tab under my workspace in my portal (in the red box shown in the picture below), is different than the one that comes by default with the workspace(```kv = Keyvault(ws)```)?

If I click on the key-vault tab (from the picture below) on my azure portal, I can see the secrets that I defined from inside the workspace (in my notebook). 
![image](https://user-images.githubusercontent.com/17963295/66070799-d6ee0b80-e506-11e9-935f-8df672740feb.png)

**Comment by alieus** [comment] 2019-10-02 18:48
@jadhosn Yes this is exactly the default Key Vault. I wonder why kv.list_secrets() isn't working for you. It certain is working on my end.

**Comment by jadhosn** [comment] 2019-10-02 20:32
> @jadhosn Yes this is exactly the default Key Vault. I wonder why kv.list_secrets() isn't working for you. It certainly is working on my end.

What's your azureml SDK version? 

On 1.0.57, ```kv.list_secrets()``` just returns the secrets that I registered from inside my notebook. It won't return any secret that I added manually from the workspace's key-vault through the portal. 

### So to reproduce: 
1. Go to your azure portal
2. Go to your workspace, click on Key Vault on the top right corner
3. Click on Secrets in the left column
4. Click on Generate/Import to add a new secret
(For this example, let's name it `test-test` and for value `i-love-azureml`)
5. Now, in your Jupyter notebook, run the following: 
```
from azureml.core.workspace import Workspace
from azureml.core.keyvault import Keyvault

# get current workspace
ws = Workspace.from_config()

# define key vault to set and retrieve secrets from the keyvault
kv = Keyvault(ws)

# Secret defined from the workspace portal
print(kv.list_secrets()) # should return [{'name': 'test-test'}], but it doesn't on v1.0.57. It returns an empty list

kv.get_secret('test-test') # returns value stored in secrets (i-love-azureml)

# add a secret from inside my notebook 
kv.set_secret(name = "jad", value ="test")
print(kv.list_secrets()) # returns [{'name': 'jad'}]
kv.get_secret('jad') # returns value stored in secrets

**Comment by v-strudm-msft** [comment] 2020-04-21 03:55
Thank you for reaching out to us.  We see this issue was not addressed and was posted some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.

**Closed by v-strudm-msft** 2020-04-21 03:55 UTC

**Comment by aaronchong888** [comment] 2021-06-07 07:54
I can still reproduce the issue on v1.20.0 of the azureml SDK:

Python & SDK version:
- Python v3.6.9
- azureml-sdk v1.20.0

Steps to reproduce:
```
from azureml.core import Workspace
ws = Workspace.from_config()

from azureml.core import Keyvault
keyvault = Keyvault(ws)

keyvault.list_secrets()
# returns an empty list, but the default key vault already has some other existing secrets stored

keyvault.set_secret(name="testingsecret", value = "Password123") 
# try to set a new secret in the notebook

keyvault.list_secrets() 
# returns [{'name': 'testingsecret'}]

keyvault.get_secret('existing-secret-name-created-on-key-vault') 
# returns existing secret value stored in the key vault
```
