### ISSUE TITLE
UserErrorException when trying to use the explain model

### ISSUE THREAD

**Issue by shivsn** [Azure/MachineLearningNotebooks#221] opened 2019-02-20 07:08 UTC
I was using the azureml locally for testing purpose but when I use the following code for understanding the feature importances it throws as error as mentioned below:
shap_values, expected_values, overall_summary, overall_imp, per_class_summary, per_class_imp = \
    retrieve_model_explanation(best_run)

UserErrorException: File with path explanation/shap_values.json was not found,
available files include: accuracy_table,confusion_matrix,outputs/model.pkl.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36c9ed64-01c3-d7d5-bbdb-8ede3f69d02e
* Version Independent ID: 01df3a5d-c87d-b629-4cfe-2ddee7f2eb06
* Content: [azureml.train.automl.automlexplainer module - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-train-automl/azureml.train.automl.automlexplainer?view=azure-ml-py#)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlexplainer.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-automl/azureml.train.automl.automlexplainer.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by mesameki** [comment] 2019-02-20 15:39
Hi @shivsn, Can you please provide us with more details on how you used AutoML and what parameters were used in your AutoML configurations so that we can reproduce the error?

**Comment by amcib** [comment] 2019-03-13 00:05
I get the same error when I have used GPU in AzureML Compute. 
I am running the auto-ml-remote-batchai azure notebook and then using the explanation component of the the auto-ml-model-explanation azure notebook. 
My AutoML configuration is:
automl_settings = {
    "iteration_timeout_minutes": 2,
    "iterations": 20,
    "n_cross_validations": 5,
    "primary_metric": 'AUC_weighted',
    "preprocess": False,
    "max_concurrent_iterations": 5,
    "verbosity": logging.INFO
}

automl_config = AutoMLConfig(task = 'classification',
                             debug_log = 'automl_errors.log',
                             path = project_folder,
                             run_configuration=conda_run_config,
                             data_script = project_folder + "/get_data.py",
                             **automl_settings
                            )

**Comment by shivsn** [comment] 2019-03-13 15:13
@

> Hi @shivsn, Can you please provide us with more details on how you used AutoML and what parameters were used in your AutoML configurations so that we can reproduce the error?

Hi @mesameki this was the AutoMLConfig used if you need more details I can share them:
AutoMLConfig(task = 'classification',
                             debug_log = 'automl_errors.log',
                             primary_metric = 'accuracy',
                             iteration_timeout_minutes = 5,
                             iterations = 10,
                             n_cross_validations = 3,
                             verbosity = logging.INFO,
                             X = X_train, 
                             y = y_train,
                             path = project_folder,
                            preprocess=True).

**Comment by wamartin-aml** [comment] 2019-03-13 15:42
Hi @shivsn, it looks like you didn't actually run the model explanation - AutoML requires you to set `model_explainability=True` when you create the config. There is an example in the notebook here: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/model-explanation/auto-ml-model-explanation.ipynb

Because that parameter wasn't passed in, the explanation didn't happen, and so the files associated with the explanation don't exist.

**Comment by ktebbe** [comment] 2019-03-28 19:09
I'm having an issue where turning on model_explainability causes the experiments to run for an absurdly long amount of time, even when iteration_timeout_minutes is set.

**Comment by wamartin-aml** [comment] 2019-03-28 19:15
Hi @ktebbe, what version of Automated ML are you using? There have been some big performance improvements in our most recent version.

**Comment by ktebbe** [comment] 2019-03-28 19:23
Hi @wamartin-aml - How do I find what version I'm using?

**Comment by wamartin-aml** [comment] 2019-03-28 19:30
From within your environment, I believe you should be able to run `pip show azureml-train-automl`. The version number should be near the top of what prints out.

**Comment by ktebbe** [comment] 2019-04-03 19:40
@wamartin-aml I'm using version 1.0.6. What's the latest version?

**Comment by wamartin-aml** [comment] 2019-04-03 19:46
Based on the pypi package, it looks like 1.0.21.1 is the latest. You can either specifically `pip install azureml-train-automl==1.0.21.1` or just `pip install azureml-train-automl --upgrade` for whatever the latest is.

A word of warning - for large datasets, particularly ones with many features (or text which Automated ML may convert into many features), model explainability is a somewhat expensive operation, which may take longer than you initially expect.

**Comment by cdotzenrod** [comment] 2019-04-12 20:45
I have the same issue as well.  I'm following all the step by steps on this sample notebook:  https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/model-explanation/auto-ml-model-explanation.ipynb  When I get to the part where I ask for model explain ability, I get error:  Expecting value: line 1 column 1 (char 0)
![azurenotebookcapture](https://user-images.githubusercontent.com/36054013/56065264-f8312480-5d39-11e9-9138-c0e777683251.JPG)

**Comment by cdotzenrod** [comment] 2019-04-12 20:49
> I have the same issue as well.  I'm following all the step by steps on this sample notebook:  https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/automated-machine-learning/model-explanation/auto-ml-model-explanation.ipynb  When I get to the part where I ask for model explain ability, I get error:  Expecting value: line 1 column 1 (char 0)

BTW - I'm using local compute context with an Azure Notebook.

**Comment by imatiach-msft** [comment] 2019-04-12 21:20
@cdotzenrod could you please post the full error message you are seeing in the notebook?  Thanks!

**Comment by cdotzenrod** [comment] 2019-04-13 04:16
I posted that dump.  Any insights?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cdotzenrod** [comment] 2019-04-16 13:47
> @cdotzenrod could you please post the full error message (eg the full stack trace in the notebook above) you are seeing in the notebook?  Thanks!

Did you figure out what the issue is?  I'm trying to get a customer demo ready and can't proceed.  Are there other walk-throughs I could do that will work with Azure Notebooks and include model explainability?  Or should I use Databricks instead of Azure Notebooks?

**Comment by imatiach-msft** [comment] 2019-04-16 13:55
@cdotzenrod sorry, I'm not sure what the issue is yet.  Could you please run:
"pip show azureml-explain-model"
and post the results here?  Also, could you try upgrading the package to latest:
pip install --upgrade azureml-explain-model
The notebook is passing our builds so I'm not quite sure what is wrong.  Are you modifying the notebook in any way, eg using a different dataset?

**Comment by imatiach-msft** [comment] 2019-04-16 13:56
also, if you are still having issues maybe we could discuss on a teams or skype call and you could share screen?

**Comment by cdotzenrod** [comment] 2019-04-16 14:17
A teams call would be good.  Let me know when you are free.  I could run those PIP commands locally but I was in the understanding that Azure Notebooks don't execute on my local machine.  Am I mistaken?  I'll go ahead and run those right now to see what I get.



Chad Dotzenrod
Data & AI Specialist
Microsoft Corp - US Health and Life Sciences

630.669.6095
chdotzen@microsoft.com

________________________________

**Comment by cdotzenrod** [comment] 2019-04-16 14:29
When I read the overview of Azure Notebooks, I'm given the impression that I don't need anything installed locally and that I have access to a virtual python env in the cloud.  Am I mistaken?


https://docs.microsoft.com/en-us/azure/notebooks/azure-notebooks-overview

[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/azure/notebooks/azure-notebooks-overview>

Overview of Azure Notebooks | Microsoft Docs<https://docs.microsoft.com/en-us/azure/notebooks/azure-notebooks-overview>
docs.microsoft.com
Overview of Azure Notebooks. 04/05/2019; 4 minutes to read; Contributors. In this article. Azure Notebooks is a free hosted service to develop and run Jupyter notebooks in the cloud with no installation.






Chad Dotzenrod
Data & AI Specialist
Microsoft Corp - US Health and Life Sciences

630.669.6095
chdotzen@microsoft.com

________________________________

**Comment by imatiach-msft** [comment] 2019-04-16 16:38
@cdotzenrod thank you for helping me repro the issue on teams.  I was able to repro and fix the issue.  It ended up being a python environment issue.  Can you please run the following:
```
from pip._internal import main as pip
pip(["install", "--upgrade", "numpy"])
pip(["install", "--upgrade", "scikit-image"])
```
And restart the kernel before rerunning the notebook?  That fixed the error for me.

**Comment by kenkadota** [comment] 2019-05-21 20:47
@shivsn There seems to be a fix, closing this bug.

**Closed by kenkadota** 2019-05-21 20:47 UTC

**Comment by adamthorne** [comment] 2020-04-18 19:50
Worth to highlight that the syntax for loading the libraries needs to include runtime it would seem:

from azureml.train.automl.runtime.automlexplainer import retrieve_model_explanation 
 See the reference info on MS site [here]([url](https://docs.microsoft.com/en-us/python/api/azureml-train-automl-runtime/azureml.train.automl.runtime.automlexplainer?view=azure-ml-py)):
