### ISSUE TITLE
PythonScriptStep `allow_reuse` when snapshot is the same and input Datasets don't change versions

### ISSUE THREAD

**Issue by JSpenced** [Azure/MachineLearningNotebooks#1284] opened 2021-01-06 18:08 UTC
I want to know if there is anyway to allow_reuse only when the snapshot is the same and the Dataset object doesn't change versions?

For example, if the Input Dataset object is version 2 (eg.. it was version 1 before and this was the only change and version 2 is a different file in blob storage.), then this will trigger a pipeline run if allow_reuse=True. But if the Input Dataset object were still version 1, then this would use the previous outputs since the snapshot and the input Dataset version are the same. 

Is there anyway to get this functionality with built-in functions or through some clever hack of passing in the dataset version as an input to the script to somehow change the hash (maybe using `hash_paths` parameter)?

**Comment by JSpenced** [comment] 2021-01-06 18:11
This is related to #771 and #379, but slightly different in that I am wondering if changing of the Dataset version can be used when hashing for `allow_reuse`.

**Comment by SturgeonMi** [comment] 2021-01-11 20:03
Hi Jeff,

Let me confirm my understanding here:

    Is it like: "you ran pipeline with dataset version1, set allow reuse = True
    then you ran pipeline again with dataset version2 (different file), set allow reuse=True. This pipeline didn't reran"?

What is your expected behavior if the dataset version is updated and you triggered a pipeline run？

**Comment by JSpenced** [comment] 2021-01-11 20:48
Yes, I want the pipeline to re-run if dataset version 2 is passed in instead of dataset version 1 (dataset is same name but version is different), but all other files/scripts remain the same. It didn't re-run, so I stopped using the allow_reuse=True.

Is the expected behavior that if you pass in version 2 instead of version 1 (and that is the only difference) that it is supposed to re-run? Maybe something was wrong with my script and I will check on it again.

**Comment by SturgeonMi** [comment] 2021-01-19 23:00
It's not expected behavior, we created a customer impediment to track the potential bug.
It should reran since the dataset version is different.
But if there is any update from your side please free to post it here.
Thanks!

**Comment by meyetman** [comment] 2021-01-20 19:39
We are closing this issue, but if you have any follow-ups, please reopen it! #please-close

**Closed by meyetman** 2021-01-20 19:39 UTC
Labels: Data4ML, Pipelines, product-issue
