### ISSUE TITLE
Datastore upload timeout 

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/MachineLearningNotebooks#1167] opened 2020-09-30 01:03 UTC
to reproduce:

```sh
!pip install --upgrade azureml-core torchvision
```

```python
from azureml.core import Workspace 

ws = Workspace.from_config()

from azureml.core import Dataset
from torchvision import datasets

ds_name = "cifar10-train"

datasets.CIFAR10(".", train=True, download=True)
# this fails
ws.get_default_datastore().upload(
    "cifar-10-batches-py", "datasets/cifar10/train"
)
ds = Dataset.File.from_files(
    (ws.get_default_datastore(), "datasets/cifar10/**")
).register(ws, ds_name)
```

output is:

```
Files already downloaded and verified
Uploading an estimated of 8 files
Uploading cifar-10-batches-py/readme.html
Uploaded cifar-10-batches-py/readme.html, 1 files out of an estimated total of 8
Uploading cifar-10-batches-py/batches.meta
Uploaded cifar-10-batches-py/batches.meta, 2 files out of an estimated total of 8
WARNING - Retrying (Retry(total=2, connect=3, read=2, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /azureml-blobstore-b0304e68-b406-492f-90b6-ae4897ecdb33/datasets/cifar10/train/data_batch_1
WARNING - Retrying (Retry(total=2, connect=3, read=2, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /azureml-blobstore-b0304e68-b406-492f-90b6-ae4897ecdb33/datasets/cifar10/train/data_batch_2
WARNING - Retrying (Retry(total=2, connect=3, read=2, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /azureml-blobstore-b0304e68-b406-492f-90b6-ae4897ecdb33/datasets/cifar10/train/data_batch_5
WARNING - Retrying (Retry(total=1, connect=3, read=1, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /azureml-blobstore-b0304e68-b406-492f-90b6-ae4897ecdb33/datasets/cifar10/train/data_batch_1
WARNING - Retrying (Retry(total=1, connect=3, read=1, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /azureml-blobstore-b0304e68-b406-492f-90b6-ae4897ecdb33/datasets/cifar10/train/data_batch_2
```

screenshot:
![image](https://user-images.githubusercontent.com/54814569/94631947-18caa280-027e-11eb-835f-02c60bdf4f66.png)

**Comment by SturgeonMi** [comment] 2020-09-30 18:38
Hi Cody, we are looking into this issue. Will update.

**Comment by lostmygithubaccount** [comment] 2020-10-05 18:34
per internal discussion tried using `Dataset.File.upload_directory` but it seemed to experience the same issue

**Comment by drewlr** [comment] 2020-10-06 16:14
@lostmygithubaccount  Having the same issue here - I guess it's due to a timeout setting on the SDK side. I remember being able to edit it with old API and getting around the issue, but not sure how to do it with this one.

https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-library-usage-patterns?view=azure-python#optional-arguments-for-client-objects-and-methods

**Comment by lostmygithubaccount** [comment] 2020-10-06 23:43
@drewlr what OS are you using? and versions of `azureml-core` and `azureml-dataprep`?

**Comment by drewlr** [comment] 2020-10-07 08:45
I'm on Windows, using

```
azure-core==1.8.2
azureml-core==1.15.0
azureml-dataprep==2.2.3
```

**Comment by myshylin** [comment] 2020-10-08 20:00
Hi,

we confirmed that this is a bug in azureml-dataprep package for both Datastore and Dataset. It is related to the request timeout calculation that causes request termination too early on slower internet connection. 

We are working on the fix and it will be included in the next package release. The way to work around it so far is to use other ways to upload data ([azure storage explorer](https://azure.microsoft.com/en-us/features/storage-explorer/), [azcopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10), azure portal web interface or [azure blob Python SDK](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10)). 

I'll update here as soon as the fix is published.

**Comment by marciomocellin** [comment] 2020-10-19 21:30
I have the same problem.
Windows
AzureML SDK Version:  1.16.0

**Comment by lostmygithubaccount** [comment] 2020-10-19 21:31
@myshylin @SturgeonMi any updates?

**Comment by SturgeonMi** [comment] 2020-10-20 19:55
@myshylin Could u help to provide the status of the fix? Thanks!

**Comment by myshylin** [comment] 2020-10-21 23:39
For now the azureml-dataprep==2.3.4 has the fix for `Dataset.File.upload_folder(...)` call (not for the Datastore one).
To use it please run `pip install --force-reinstall azureml-dataprep==2.3.4` after installing azureml-core or azureml-sdk.

The fix for azureml-core and datastore upload should be released on Monday (10/26).

**Comment by myshylin** [comment] 2020-10-28 17:54
The issue should be fixed now for both datastore and dataset upload with the latest version:
```
azureml-dataprep == 2.4.2
azureml-core == 1.17.0
```

**Comment by meyetman** [comment] 2020-11-06 17:55
#please-close

**Closed by meyetman** 2020-11-06 17:55 UTC
Labels: Data4ML, product-issue
