### ISSUE TITLE
Retrieve best model from HyperDriveStep within pipeline

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#269] opened 2019-03-26 07:41 UTC
I'm trying to integrate hyperdrive into an end-to-end pipeline.

After HyperDriveStep step runs, I'd like to register the best run's model to the service.

Previously, I followed [this notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/pipeline-style-transfer/pipeline-style-transfer.ipynb) (snippet below), but I'm not sure how I'd go about doing this in a pipeline.
- It would have to be a downstream step right?
- What is the best practice way to fetch run data of one pipeline step from another? Similar to the below?

```
best_run = hyperdrive_run.get_best_run_by_primary_metric()
model = best_run.register_model(model_name = 'pytorch-hymenoptera', model_path = 'outputs/model.pt')
```

This notebook, [Azure Machine Learning Pipeline with HyperDriveStep](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-parameter-tuning-with-hyperdrive.ipynb) is a great intro, but is missing what I need.

**Comment by akshay-0** [comment] 2019-03-26 21:12
If you provide a blob for metrics_output parameter in HyperDriveStep, it'll create a json file containing metrics for all runs. You could then parse the file in a downstream step.

```py
hd_step = HyperDriveStep(
    name="hyperdrive_module",
    hyperdrive_run_config=hd_config,
    estimator_entry_script_arguments=['--data-folder', data_folder],	
    inputs=[data_folder],
    metrics_output=PipelineData("metrics", datastore=def_blob_store))
```

We have some work planned to improve this experience.

**Comment by swanderz** [comment] 2019-04-02 20:29
@akshay-0 I spent all of yesterday and some of today trying to get the `metrics_output` working to no avail. Is anything here look off?

check out [this commit ](https://github.com/swanderz/MachineLearningNotebooks/tree/62f59adfcc1d990beb7f74087cc64d4788bbbd9d/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines)where I try to implement using @rastala 's [`aml-pipelines-parameter-tuning-with-hyperdrive.ipynb`](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-parameter-tuning-with-hyperdrive.ipynb)


metrics.py is just printing cwd and listdir for the script dir and the input_dir.
this is the error message for `80_driver_log.txt`

```
all args:  Namespace(input_dir='/mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/e58c9df3-1cc4-4ba1-9c14-b7707a554efd/mounts/workspaceblobstore/azureml/e88e2b6b-53d6-4d95-bf8d-57a222164932/metrics', output_dir='/mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/e58c9df3-1cc4-4ba1-9c14-b7707a554efd/mounts/workspaceblobstore/azureml/e58c9df3-1cc4-4ba1-9c14-b7707a554efd/output')
cwd: /mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/e58c9df3-1cc4-4ba1-9c14-b7707a554efd/mounts/azureml_project_share/azureml/e58c9df3-1cc4-4ba1-9c14-b7707a554efd
dir of cwd ['.ipynb_checkpoints', '20news.pkl', 'aml-pipelines-data-transfer.ipynb', 'aml-pipelines-getting-started.ipynb', 'aml-pipelines-how-to-use-azurebatch-to-run-a-windows-executable.ipynb', 'aml-pipelines-parameter-tuning-with-hyperdrive.ipynb', 'aml-pipelines-publish-and-run-using-rest-endpoint.ipynb', 'aml-pipelines-setup-schedule-for-a-published-pipeline.ipynb', 'aml-pipelines-use-adla-as-compute-target.ipynb', 'aml-pipelines-use-databricks-as-compute-target.ipynb', 'aml-pipelines-with-data-dependency-steps.ipynb', 'aml_config', 'azureml-logs', 'azureml-setup', 'compare.py', 'data', 'extract.py', 'metrics.py', 'outputs', 'testdata.txt', 'tf-mnist', 'tf_mnist.py', 'train-db-dbfs.py', 'train-db-local.py', 'train.py', 'utils.py']
input_dir: /mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/e58c9df3-1cc4-4ba1-9c14-b7707a554efd/mounts/workspaceblobstore/azureml/e88e2b6b-53d6-4d95-bf8d-57a222164932/metrics


The experiment failed. Finalizing run...
Logging experiment finalizing status in history service
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.2506852149963379 seconds
Traceback (most recent call last):
  File "azureml-setup/context_manager_injector.py", line 161, in <module>
    execute_with_context(cm_objects, options.invocation)
  File "azureml-setup/context_manager_injector.py", line 90, in execute_with_context
    runpy.run_path(sys.argv[0], globals(), run_name="__main__")
  File "/azureml-envs/azureml_2ffb57cb85eac5669f4d09127f2be92f/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/azureml-envs/azureml_2ffb57cb85eac5669f4d09127f2be92f/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/azureml-envs/azureml_2ffb57cb85eac5669f4d09127f2be92f/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "metrics.py", line 21, in <module>
    print("dir of input_dir", os.listdir(args.input_dir))
NotADirectoryError: [Errno 20] Not a directory: '/mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/e58c9df3-1cc4-4ba1-9c14-b7707a554efd/mounts/workspaceblobstore/azureml/e88e2b6b-53d6-4d95-bf8d-57a222164932/metrics'
```

**Comment by akshay-0** [comment] 2019-04-02 21:25
Can you please share pipeline run id? We have identified one issue where metrics output was incorrectly produced as empty JSON. Fix for that issue is currently in deployment. But the error here seems different. Pipeline run id will help us investigate further.

**Comment by swanderz** [comment] 2019-04-02 22:18
@akshay-0, I totally think I'm experiencing the first issue based on the `stdoutlog.txt`. [This gist](https://gist.github.com/swanderz/0816c3a38dd5a0522a2a4f04a1b042ba) that has:
- the pipeline code and
- the `stdoutlog.txt` from the Hyperdrive step

The example you're sharing uses a `DataReference` object, have you ever gotten it to work as a `PipelineData` object? I'd like to do is have the metrics JSON saved into a `PipelineData` object, so that a downstream step can select the best iteration and use it's model to do batch scoring.

```
data_metrics = PipelineData("metrics", datastore=def_blob_store)
hd_step = HyperDriveStep(
    name="hyperdrive_module",
    hyperdrive_run_config=hd_config,
    estimator_entry_script_arguments=['--data-folder', data_folder],
    inputs=[data_folder],
    metrics_output = data_metrics,
    allow_reuse=True
)

metrics_step = PythonScriptStep(
    name='get_metrics',
    script_name='metrics.py',
    arguments=['--input_dir', data_metrics,
               '--output_dir', data_output],
    compute_target=compute_target,
    inputs=[data_metrics],
    outputs=[data_output],
    source_directory=os.getcwd(),
    allow_reuse=True
)

**Comment by akshay-0** [comment] 2019-04-02 22:27
You're right. You're experiencing the same issue where metrics output was incorrectly produced as empty JSON. We're currently rolling out a fix for that, Will update here once it's available in all regions.

**Comment by akshay-0** [comment] 2019-04-04 18:01
Fix has been rolled out to few regions including westus2. You can try it now and let me know if you still face any issues.

Re: PipelineData, it works with PipelineData as well as DataReference.

**Comment by swanderz** [comment] 2019-04-05 05:11
@akshay-0 thanks to you and your team for working to resolve this issue.

I can see the metrics json in the `stdoutlog.txt` but I can't access it using a `PythonScriptStep` or with a `DataTransferStep`.
Here's a [gist ](https://gist.github.com/swanderz/71643c7cbce764834cee14d867858ffc) with the error's from both.
DataTransferStep says `ErrorCode=UserErrorSourceBlobNotExist`
PythonScriptSteps says `NotADirectoryError: [Errno 20] Not a directory: '/mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/6bb6298b-6a5d-49d0-b2af-8a734c44f9c1/mounts/workspaceblobstore/azureml/3c76ab4e-51e5-46a8-bf36-ca9789c581ba/hyperdrive_metrics'`

**Comment by swanderz** [comment] 2019-04-05 16:46
@akshay-0 when I try to do the same thing with the [aml-pipelines-parameter-tuning-with-hyperdrive.ipynb](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-parameter-tuning-with-hyperdrive.ipynb) like i had earlier, I still get the same as with my own experiment.

This is the same error that I get when attempt to write to a PipelineData without first running the following
```
os.makedirs(args.output_dir, exist_ok=True)
```

Is it possible that the json is saved in the dir of the PipelineRun run rather than `run_id/metrics_data` directory? I know there's a way to navigate to this and look, but I can't remember how to get there...

![image](https://user-images.githubusercontent.com/8158673/55639701-d99dbd00-577e-11e9-91d9-040c759c255f.png)

**Comment by akshay-0** [comment] 2019-04-05 18:12
Can you please share the definition of hyperdrive_metrics and/or pipeline run id?

**Comment by swanderz** [comment] 2019-04-05 18:38
I'm pretty confident that the JSON is being saved in the parent directory of the PipelineData reference. In this case, the JSON is empty, but I expect it to be because `tf_mnist.py` doesn't log any metrics.

Is this a sufficient amount of the run id for you?
`8ae6cdfb-6bb6-4390-8647-34a21c16b06f`

here's the [exact code](https://github.com/swanderz/MachineLearningNotebooks/commit/e1ef8a54f0e290a554db12fca224e2df92268d6c). basically it is a copy of @rastala's [Azure Machine Learning Pipeline with HyperDriveStep](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-parameter-tuning-with-hyperdrive.ipynb) except i've added the following:
```
data_metrics = PipelineData("metrics", datastore=def_blob_store)
data_output = PipelineData("output", datastore=def_blob_store)

hd_step = HyperDriveStep(
    name="hyperdrive_module",
    hyperdrive_run_config=hd_config,
    estimator_entry_script_arguments=['--data-folder', data_folder],
    inputs=[data_folder],
    metrics_output = data_metrics,
    allow_reuse=True
)

metrics_step = PythonScriptStep(
    name='get_metrics',
    script_name='metrics.py',
    arguments=['--input_dir', data_metrics,
               '--output_dir', data_output],
    compute_target=compute_target,
    inputs=[data_metrics],
    outputs=[data_output],
    source_directory=os.getcwd(),
    allow_reuse=True
)
```

this is metrics.py
```
import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument('--input_dir', dest="input_dir", default = "C://temp/attrition_pipe/output")
parser.add_argument('--output_dir', dest="output_dir", default = "C://temp/attrition_pipe/output")

args = parser.parse_args()
print("all args: ", args)

cwd = os.getcwd()
print("cwd:", cwd)
print("dir of cwd", os.listdir(cwd))
parent = os.path.dirname(args.input_dir)
print("input_dir_parent:", parent)
print("dir of input_dir_parent:", os.listdir( parent))


with open(os.path.join(parent, 'metrics')) as f:
    metrics = json.load(f)

print(metrics)
```

here's `80_driver_log.txt` for the `get_metrics` step.
```
all args:  Namespace(input_dir='/mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/e8e790e0-ca91-433f-b5ef-cf24399d38ea/mounts/workspaceblobstore/azureml/e88e2b6b-53d6-4d95-bf8d-57a222164932/metrics', output_dir='/mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/e8e790e0-ca91-433f-b5ef-cf24399d38ea/mounts/workspaceblobstore/azureml/e8e790e0-ca91-433f-b5ef-cf24399d38ea/output')
cwd: /mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/e8e790e0-ca91-433f-b5ef-cf24399d38ea/mounts/azureml_project_share/azureml/e8e790e0-ca91-433f-b5ef-cf24399d38ea
dir of cwd ['.ipynb_checkpoints', '20news.pkl', 'aml-pipelines-data-transfer.ipynb', 'aml-pipelines-getting-started.ipynb', 'aml-pipelines-how-to-use-azurebatch-to-run-a-windows-executable.ipynb', 'aml-pipelines-parameter-tuning-with-hyperdrive.ipynb', 'aml-pipelines-publish-and-run-using-rest-endpoint.ipynb', 'aml-pipelines-setup-schedule-for-a-published-pipeline.ipynb', 'aml-pipelines-use-adla-as-compute-target.ipynb', 'aml-pipelines-use-databricks-as-compute-target.ipynb', 'aml-pipelines-with-data-dependency-steps.ipynb', 'aml_config', 'azureml-logs', 'azureml-setup', 'compare.py', 'data', 'extract.py', 'metrics.py', 'outputs', 'testdata.txt', 'tf-mnist', 'tf_mnist.py', 'train-db-dbfs.py', 'train-db-local.py', 'train.py', 'utils.py']
input_dir_parent: /mnt/batch/tasks/shared/LS_root/jobs/avadevitsmlsvc/azureml/e8e790e0-ca91-433f-b5ef-cf24399d38ea/mounts/workspaceblobstore/azureml/e88e2b6b-53d6-4d95-bf8d-57a222164932
dir of input_dir_parent: ['metrics']
{}


The experiment completed successfully. Finalizing run...
Logging experiment finalizing status in history service
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.2506706714630127 seconds
```

**Comment by akshay-0** [comment] 2019-04-05 19:11
I believe the issue is that you're trying to treat data_metrics as directory whereas it's a file. For instance, the ` source_reference_type='directory',` in below code.

```py
transfer_metrics_step = DataTransferStep(
    name="transfer_metrics",
    source_data_reference=hyperdrive_metrics,
    destination_data_reference=output_dir,
    source_reference_type='directory',
    destination_reference_type='directory',
    compute_target=data_factory_compute,
    allow_reuse=pipeline_reuse
)
```

I just tried below code and it seems to work fine:

```py
metrics_output = PipelineData("metrics_output", datastore=ds)

step1 = HyperDriveStep(
	name="hyperdrive_step",
	hyperdrive_run_config=hd_config,
	estimator_entry_script_arguments=['--data-folder', data_folder],
	inputs=[data_folder],
	metrics_output=metrics_output)

step2_output = DataReference(
	datastore=ds,
	data_reference_name='hd_metrics',
	path_on_datastore='hd_metrics')

step2 = DataTransferStep(
	name='hd_metrics_copy',
	source_data_reference=metrics_output,
	destination_data_reference=step2_output,
	compute_target=data_factory_compute)
```

I'm going to look at exact execution of your pipeline, but you may want to try it in the meantime.

**Comment by swanderz** [comment] 2019-04-05 20:05
@akshay-0 yeah I'm seeing the same thing now.

Thanks for you help through all of this. It seems my takeaway is that:
- PipelineData objects are intended by default to save single objects, and 
- the SDK will do exactly that if i come across a param like the `metrics_output` in the future.

What's the best way to make this clear to future users? Perhaps adding your output steps above to the Azure Machine Learning Pipeline with HyperDriveStep notebook?

Perhaps if i was a better dev, I could have figured this out more quickly, but I was lead astray by the following:
- every [pipeline ipynb's in this repo](https://github.com/Azure/MachineLearningNotebooks/tree/master/how-to-use-azureml/machine-learning-pipelines) only uses `PipelineData` objects as directories to save files into,
- the error message when I tried to pass a filename (`metrics_output.json`) to the `name` parameter of `PipelineData`: "your cannot use `.`'s in the name parameter."
 `metrics_ouput = PipelineData("hd_metrics", datastore=def_blob_store)`, and
- reading the documentation's description (see below) to mean:
    "please tell us the folder where you would like the JSON to be saved"

> [`metrics_output`](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.hyper_drive_step.hyperdrivestep?view=azure-ml-py#parameters) :
> `PipelineData` or `azureml.data.data_reference.DataReference` or `azureml.pipeline.core.graph.OutputPortBinding`
> Optional value specifying the location to store HyperDrive run metrics as a JSON file

**Comment by akshay-0** [comment] 2019-04-05 20:08
Thanks for your feedback! We have some work planned in near future to get rid of metrics_output and make it more streamlined. Including, in case of hyperdrive, making it easier to retrieve best run (inside the pipeline).

**Comment by swanderz** [comment] 2019-04-05 22:35
@akshay-0 you're my hero. Any chance you've got 30 min on your calendar to sync with me? I have some question I haven't yet gotten an answer to that would really accelerate our adoption of the SDK. @heatherbshapiro I think could help set it up. Cheers!

**Comment by sanpil** [comment] 2019-04-08 22:37
@swanderz please send your questions to @heatherbshapiro or me. @akshay-0 is on call and may not be able to honor other commitments. But we will make sure he gets to see your questions.

**Closed** 2019-07-11 23:15 UTC

**Comment by masgra** [comment] 2021-01-22 08:38
> 
> 
> Thanks for your feedback! We have some work planned in near future to get rid of metrics_output and make it more streamlined. Including, in case of hyperdrive, making it easier to retrieve best run (inside the pipeline).

@akshay-0  I am curious, is there already a method to retrieve the bet run inside a pipeline after running the hyperdrive step? 
I always find it a bit of a hassle storing the metrics_ouput as a separate file when I already log these metrics, parameters and models during the runs.

**Comment by swanderz** [comment] 2021-01-22 15:59
> I always find it a bit of a hassle storing the metrics_ouput as a separate file when I already log these metrics, parameters and models during the runs.

Seconded! What is the roadmap for Pipelines in general?

**Comment by sonnypark** [comment] 2021-01-22 17:54
HyperDriveStep started supporting model outputs. You can check the sample notebook:
https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-parameter-tuning-with-hyperdrive.ipynb
![image](https://user-images.githubusercontent.com/10220522/105526658-8c624680-5c97-11eb-8711-677d7d21cbf6.png)

For more details on the TrainingOutput:
https://docs.microsoft.com/en-us/python/api/azureml-pipeline-core/azureml.pipeline.core.graph.trainingoutput?view=azure-ml-py

**Comment by swanderz** [comment] 2021-01-22 18:53
> supporting model outputs

@sonnypark way cool! could we use this construct to access _any_ file from a child run? provided we we pass the `training_output` param with the filename to the `PipelineData`?

**Comment by sonnypark** [comment] 2021-01-23 01:17
@swanderz the model_file would accept string as in the description:
![image](https://user-images.githubusercontent.com/10220522/105564089-7bd0c100-5cd5-11eb-97d9-16c70e90e40b.png)

Need to confirm with HyperDrive team what exactly model_file would do. :) let me get back to you.

**Comment by jahuang1** [comment] 2021-01-23 04:49
@swanderz You should be able to use TrainingOutput to access any file that is located in the outputs/ folder (and its subfolders). You would need to create a new PipelineData object for each file and pass in its filepath via model_file, and add that to the outputs argument in HyperDriveStep.

**Comment by jeydn** [comment] 2021-02-11 15:46
I am having the same issues. Trying to use the HyperDriveStep and then just registering the best performing model. If I understand it correctly, it is not possible to access the HyperDriveRun, which holds the best_child_by_primary_metric, from the PipelineRun?
I have been trying to find an easy way out here but I guess we need to go the route of using the TrianingOutput. Or is there an obvious solution that I am missing?

**Comment by swanderz** [comment] 2021-02-11 16:30
@jeydn, [here is a gist](https://gist.github.com/swanderz/afa78a32a327e6e562d1821313819cc2) of how we currently get the best model from a `HyperdriveStep`. Basically you can get the run_id and metrics from the `hyperdrive_json`.

However, I do believe the `training_output` described above is a "simpler" way  to go. Up to you!

**Comment by CakmakMuhammet** [comment] 2021-04-27 07:54
Hi
I want to load metrics from HyperDriveSteps to the next step in Azure ML Pipeline, but I couldnot manage. I used this [HyperDriveSteps notebook](https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-parameter-tuning-with-hyperdrive.ipynb) but it is not enough to reach my goal. Do you have any suggestions?  
![1](https://user-images.githubusercontent.com/73171167/116205899-7f456f80-a73e-11eb-95da-62e529f81faa.PNG)
![2](https://user-images.githubusercontent.com/73171167/116205905-7fde0600-a73e-11eb-8c3f-3207cc8ff59c.PNG)

**Comment by julianaddison** [comment] 2021-04-28 02:23
I'm facing a similar issue. Previously used `HyperDriveStepRun` to retrieve the best model in a pipeline. However it's recently been throwing a Service invocation timed out error. Somewhat puzzled. Would you have any idea what the error means?

The pipeline:

![Screenshot 2021-04-28 at 9 58 55 AM](https://user-images.githubusercontent.com/32608788/116336399-0f50eb00-a80b-11eb-83fb-9121662028e7.png)

Step 3, `hyperdrive_save_best_model.py`

![Screenshot 2021-04-28 at 10 06 36 AM](https://user-images.githubusercontent.com/32608788/116336418-17a92600-a80b-11eb-82bd-ab4e51793d52.png)

The error is thrown in Step 3 at line 
`step_run = HyperDriveStepRun(step_run=pipeline_run.find_step_run('model_training_with_hyperdrive')[0])`
![Screenshot 2021-04-28 at 10 09 48 AM](https://user-images.githubusercontent.com/32608788/116336465-2f80aa00-a80b-11eb-97fa-2f619175d62a.png)

I'm able to find the step in the pipeline by running `pipeline_run.find_step_run('model_training_with_hyperdrive')[0].get_details()`

which returns the output below
`{'runId': '81afda1d-e09a-4b66-9916-a70d31fe5aaf', 'status': 'Completed', 'startTimeUtc': '2021-04-26T10:04:55.388077Z', 'endTimeUtc': '2021-04-26T12:02:13.912549Z', 'properties': {'ContentSnapshotId': 'f60b2327-8e65-4245-ae9d-ad1d15052db9', 'StepType': 'HyperDriveStep', 'ComputeTargetType': 'HyperDrive', 'azureml.moduleid': '1997d65f-e755-4b48-b7b6-802cebe0e932', 'azureml.runsource': 'azureml.StepRun', 'azureml.nodeid': '1b54a211', 'azureml.pipelinerunid': '4305e2b4-5695-4736-b081-6710b3e7cb64'}, 'inputDatasets': [], 'logFiles': {'logs/azureml/executionlogs.txt': 'https://cerespalmml0992777240.blob.core.windows.net/azureml/ExperimentRun/dcid.81afda1d-e09a-4b66-9916-a70d31fe5aaf/logs/azureml/executionlogs.txt?sv=2019-02-02&sr=b&sig=fQHeUuUTSKkh7RXUMDIr59sqvwXhzWVPBNXp4vaQ%2F%2F4%3D&st=2021-04-26T11%3A57%3A26Z&se=2021-04-26T20%3A07%3A26Z&sp=r', 'logs/azureml/stderrlogs.txt': 'https://cerespalmml0992777240.blob.core.windows.net/azureml/ExperimentRun/dcid.81afda1d-e09a-4b66-9916-a70d31fe5aaf/logs/azureml/stderrlogs.txt?sv=2019-02-02&sr=b&sig=Re57T4Nx1MERInO8xXTGQ7gY%2BFmxfpQKklTPSbV40ig%3D&st=2021-04-26T11%3A57%3A26Z&se=2021-04-26T20%3A07%3A26Z&sp=r', 'logs/azureml/stdoutlogs.txt': 'https://cerespalmml0992777240.blob.core.windows.net/azureml/ExperimentRun/dcid.81afda1d-e09a-4b66-9916-a70d31fe5aaf/logs/azureml/stdoutlogs.txt?sv=2019-02-02&sr=b&sig=cQ5eMV8tG%2BsmJDAd9AYvtNkvVssq3YdcP4CGIsQn6MA%3D&st=2021-04-26T11%3A57%3A26Z&se=2021-04-26T20%3A07%3A26Z&sp=r'}}`

**Comment by lostmygithubaccount** [comment] 2021-04-28 14:11
hi @julianaddison, would you mind opening a new issue for this?
