### ISSUE TITLE
Pytorch Framework Version 1.4 does not work.

### ISSUE THREAD

**Issue by calebheinzman** [Azure/MachineLearningNotebooks#888] opened 2020-03-26 00:13 UTC
The framework_version='1.4' for the Pytorch estimator does not work. All the documentation says that it should work.

**Comment by GiftA-MSFT** [comment] 2020-03-26 03:34
@calebheinzman we will review your feedback and get back to you shortly. Thanks.

**Comment by GiftA-MSFT** [comment] 2020-03-26 22:19
@calebheinzman it seems framework_version='1.4' isn't supported at the moment, but I am trying to confirm this information.

**Comment by GiftA-MSFT** [comment] 2020-03-26 22:23
@danielsc @maxluk can you please help to confirm?

**Comment by GiftA-MSFT** [comment] 2020-03-26 22:27
duplicate of [[887](https://github.com/Azure/MachineLearningNotebooks/issues/887)].

**Closed by GiftA-MSFT** 2020-03-26 22:27 UTC
Labels: cxp, machine-learning/svc, product-question, triaged
