### ISSUE TITLE
[feature request] Provide a way to specify a custom training environment in AutoML

### ISSUE THREAD

**Issue by marcindulak** [Azure/MachineLearningNotebooks#1315] opened 2021-02-02 09:21 UTC
`As a user performing an AutoML training run using azureml-sdk, I want to specify a versioned, custom execution environment (e.g. using conda, pip, docker), so that I can repeat the AutoML training run later or use the created model without the need for adjusting the azureml-sdk dependencies`

References:

https://github.com/Azure/MachineLearningNotebooks/issues/842
https://github.com/Azure/MachineLearningNotebooks/issues/1263
https://github.com/Azure/MachineLearningNotebooks/issues/1297

**Comment by CESARDELATORRE** [comment] 2021-02-03 18:05
Hi @lostmygithubaccount (Cody), I fully agree and yes, this feature request is on our plan in the next features we're planning to implement in the upcoming weeks. Thanks for the additional references to link the feature request to.

**Comment by CESARDELATORRE** [comment] 2021-02-03 18:11
@marcindulak It'd be great if you can elaborate on your particular scenarios where you need this feature so we can take it into account when implementing this feature. Thanks.

**Comment by CESARDELATORRE** [comment] 2021-02-03 20:41
@marcindulak, if possible, can you contact me through email so we gather additional detailed feedback from you about this subject?
**to: cesardl at microsoft.com**

Thanks,

**Comment by CESARDELATORRE** [comment] 2021-02-04 00:13
Closing this FEATURE REQUEST since we're already tracking it.

**Comment by lostmygithubaccount** [comment] 2021-02-08 16:37
reopen per new policy

**Comment by CESARDELATORRE** [comment] 2021-04-07 01:21
Closing this issue. After discussing it with the team, since the request is to provide a CUSTOM/USER's environment (not a CURATED ENVIRONMENT).

This is something that we explicitly don't allow by design.

AutoML training happens on curated environments as defined by AutoML and is not intended to be run with user environments.

**Closed by CESARDELATORRE** 2021-04-07 01:21 UTC
Labels: Auto ML, feature-request, product-gap

**Comment by marcindulak** [comment] 2021-04-07 06:11
If the story is changed to remove the mention of CURATED, can it be supported?

```As a user performing an AutoML training run using azureml-sdk, I want to specify a versioned execution environment, so that I can repeat the AutoML training run later or use the created model without the need for adjusting the azureml-sdk dependencies```
