### ISSUE TITLE
ParallelRunStep not processing batches

### ISSUE THREAD

**Issue by MelissaKR** [Azure/MachineLearningNotebooks#1429] opened 2021-04-13 13:51 UTC
Referencing #1405 I've tried to run the same code with the same dependencies and environment with a smaller similar dataset after two weeks, and now I'm getting the following error in sys > error > _main:

Traceback (most recent call last):
File "/mnt/batch/tasks/shared/LS_root/jobs//azureml//wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 237, in check
self.task_manager.set_task_visible(result)
File "/mnt/batch/tasks/shared/LS_root/jobs//azureml//wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 135, in set_task_visible
raise exc
File "/mnt/batch/tasks/shared/LS_root/jobs//azureml/***/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 128, in set_task_visible
task = self.agent_state.picked_tasks[(result.task_id, result.dequeue_count)]
KeyError: (187, 1)
2021-04-13 03:25:50,285|ERROR|254|140325028292352|Failed to set task visible because of (195, 1).

I get a bunch of these for each node with different KeyError values. The error for each process look like this:

2021-04-13 03:23:05,649|ERROR|334|Stop for run() unable to finish within 90 seconds for {"agent": "process000", "task_id": 16, "dequeue_count": 1, "total": 2, "succeeded": 0, "method": "run", "exc_type": "", "message": "", "detail": "", "start_time": "2021-04-13T03:21:35.275058", "duration": 90.31819200515747, "process_time": 117.17833209800001, "run_method_time": 90.31819200515747, "status": "RUN_TIMEOUT"}.

I'm wondering if something with azure ml packages has changed. I was using version 1.20 before, but trying with 1.26 for - azureml-sdk, azureml-core, azureml-dataset-runtime[pandas, fuse], and azureml-defaults didn't help. The other thing that is interesting is I'm using Python3.7 in my environment but the error messages are for python3.8.

**Comment by MelissaKR** [comment] 2021-04-13 17:53
I'd appreciate any insights into these errors, as I really need to get this part done.

**Comment by MelissaKR** [comment] 2021-04-15 20:11
Sorry for asking again, but I **urgently** need to fix this pipeline. Would appreciate any help with fixing this problem. 

As I mentioned, the same code with the same dataset was working just fine a couple of weeks ago, and I also tried with newer versions of azure ml sdk with no luck. So I'm guessing something related to the pipeline itself has been changed.

**Comment by tracychms** [comment] 2021-04-15 22:36
The error message indicates your scoring script run timeout. Have you tried to increase run_invocation_timeout and rerun? Also, is there any log you added in scoring script that can tell why it's timing out?

**Comment by MelissaKR** [comment] 2021-04-15 22:53
Thanks for your response @tracychms! I am running it with the default run_invocation_timeout value. As I mentioned, I came back a couple weeks later to run the same code, and apparently, there's something wrong with the task_manager. I checked all the dependencies installed in the docker for the successful run, and tried to match those, but even then it fails. 

Here is what I get in sys > error > main file for each node:

```
2021-04-15 22:05:26,715|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:05:26,743|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:05:26,744|ERROR|255|139773019682560|stderr: Already registered authentication for run id: 94a35e75-bdae-43bf-ac15-f6c37b6e1c0f
terminate called without an active exception
2021-04-15 22:05:27,959|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:05:27,962|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:05:27,992|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:05:29,146|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:05:29,154|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:05:31,422|ERROR|255|139773019682560|stderr: Already registered authentication for run id: 94a35e75-bdae-43bf-ac15-f6c37b6e1c0f
terminate called without an active exception
2021-04-15 22:05:31,425|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:06:05,631|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:06:07,143|ERROR|255|139771934123776|Failed to set task visible because of (86, 1).
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/#####/azureml/######/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 247, in check
    self.task_manager.set_task_visible(result)
  File "/mnt/batch/tasks/shared/LS_root/jobs/#####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 134, in set_task_visible
    raise exc
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/######/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 128, in set_task_visible
    task = self.agent_state.picked_tasks[(result.task_id, result.dequeue_count)]
KeyError: (86, 1)
2021-04-15 22:06:14,911|ERROR|255|139773019682560|stderr: Already registered authentication for run id: 94a35e75-bdae-43bf-ac15-f6c37b6e1c0f
terminate called without an active exception
2021-04-15 22:06:15,564|ERROR|255|139771934123776|Failed to set task visible because of (114, 1).
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/#####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 247, in check
    self.task_manager.set_task_visible(result)
  File "/mnt/batch/tasks/shared/LS_root/jobs/#####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 134, in set_task_visible
    raise exc
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 128, in set_task_visible
    task = self.agent_state.picked_tasks[(result.task_id, result.dequeue_count)]
KeyError: (114, 1)
2021-04-15 22:06:22,040|ERROR|255|139773019682560|stderr: Already registered authentication for run id: 94a35e75-bdae-43bf-ac15-f6c37b6e1c0f
terminate called without an active exception
2021-04-15 22:06:22,613|ERROR|255|139771934123776|Failed to set task visible because of (104, 1).
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 247, in check
    self.task_manager.set_task_visible(result)
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 134, in set_task_visible
    raise exc
  File "/mnt/batch/tasks/shared/LS_root/jobs/#####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 128, in set_task_visible
    task = self.agent_state.picked_tasks[(result.task_id, result.dequeue_count)]
KeyError: (104, 1)
2021-04-15 22:07:40,410|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:07:40,881|ERROR|255|139771934123776|Failed to set task visible because of (146, 1).
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 247, in check
    self.task_manager.set_task_visible(result)
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 134, in set_task_visible
    raise exc
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/ask_manager.py", line 128, in set_task_visible
    task = self.agent_state.picked_tasks[(result.task_id, result.dequeue_count)]
KeyError: (146, 1)
2021-04-15 22:07:42,753|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:07:42,765|ERROR|255|139773019682560|stderr: Already registered authentication for run id: 94a35e75-bdae-43bf-ac15-f6c37b6e1c0f
terminate called without an active exception
2021-04-15 22:07:43,316|ERROR|255|139771934123776|Failed to set task visible because of (138, 1).
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 247, in check
    self.task_manager.set_task_visible(result)
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 134, in set_task_visible
    raise exc
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 128, in set_task_visible
    task = self.agent_state.picked_tasks[(result.task_id, result.dequeue_count)]
KeyError: (138, 1)
2021-04-15 22:07:44,351|ERROR|255|139771934123776|Failed to set task visible because of (131, 1).
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 247, in check
    self.task_manager.set_task_visible(result)
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 134, in set_task_visible
    raise exc
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/ask_manager.py", line 128, in set_task_visible
    task = self.agent_state.picked_tasks[(result.task_id, result.dequeue_count)]
KeyError: (131, 1)
2021-04-15 22:07:46,570|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:07:46,573|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:07:46,576|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:07:47,701|ERROR|255|139773019682560|stderr: Already registered authentication for run id: 94a35e75-bdae-43bf-ac15-f6c37b6e1c0f
terminate called without an active exception
2021-04-15 22:07:48,263|ERROR|255|139771934123776|Failed to set task visible because of (135, 1).
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 247, in check
    self.task_manager.set_task_visible(result)
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 134, in set_task_visible
    raise exc
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 128, in set_task_visible
    task = self.agent_state.picked_tasks[(result.task_id, result.dequeue_count)]
KeyError: (135, 1)
2021-04-15 22:07:48,836|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:07:49,296|ERROR|255|139771934123776|Failed to set task visible because of (144, 1).
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 247, in check
    self.task_manager.set_task_visible(result)
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 134, in set_task_visible
    raise exc
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 128, in set_task_visible
    task = self.agent_state.picked_tasks[(result.task_id, result.dequeue_count)]
KeyError: (144, 1)
2021-04-15 22:07:50,618|ERROR|255|139771934123776|Failed to set task visible because of (152, 1).
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 247, in check
    self.task_manager.set_task_visible(result)
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 134, in set_task_visible
    raise exc
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/task_manager.py", line 128, in set_task_visible
    task = self.agent_state.picked_tasks[(result.task_id, result.dequeue_count)]
KeyError: (152, 1)
2021-04-15 22:07:51,141|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:07:51,156|ERROR|255|139773019682560|stderr: terminate called without an active exception
2021-04-15 22:07:51,774|ERROR|255|139771934123776|Failed to set task visible because of (145, 1).
.
.
.
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 338, in start_agent_monitor
    self.monitor_agents()
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 299, in monitor_agents
    self.check()
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/agent_manager.py", line 258, in check
    self.processes.remove(proc)
ValueError: list.remove(x): x not in list
2021-04-15 22:08:14,629|ERROR|255|139771934123776|Failed to start agent manager with ValueError on round 0.
```

Previously I would only get a bunch of `|ERROR|152|139967160071936|stderr: terminate called without an active exception` at the beginning, but it would never run into exceptions.

**Comment by psavdekar** [comment] 2021-04-15 23:01
Can you please confirm 
1. if job_progress_overview file indicates that tasks were created?
2. Was there any task successfully processed?

Beside this, I would recommend checking master_role log and logs in logs/user folder.

Meanwhile we will look into "Failed to set task visible" issue.

**Comment by MelissaKR** [comment] 2021-04-15 23:15
Thanks @psavdekar , here's what the job_progress_overview file looks like:

```
2021-04-15T22:03:32.226929 Start the simulator.
2021-04-15T22:03:34.285780 The overviewer on 10.0.0.4 started.
2021-04-15T22:03:54.767763 Scheduling finished. Scheduled 276 mini batches in 22 seconds. There are 276 tasks with 551 items.
2021-04-15T22:03:54.899666 No task has been processed yet.
2021-04-15T22:04:05.237617 No task has been processed yet.
2021-04-15T22:04:15.745348 No task has been processed yet.
2021-04-15T22:04:26.199978 No task has been processed yet.
2021-04-15T22:04:36.777685 No task has been processed yet.
2021-04-15T22:04:47.295999 No task has been processed yet.
2021-04-15T22:04:57.595692 No task has been processed yet.
2021-04-15T22:05:08.054346 No task has been processed yet.
2021-04-15T22:05:18.437680 No task has been processed yet.
2021-04-15T22:05:28.780714 No task has been processed yet.
2021-04-15T22:05:39.023022 No task has been processed yet.
2021-04-15T22:05:49.410236 No task has been processed yet.
2021-04-15T22:05:59.904125 No task has been processed yet.
2021-04-15T22:06:10.460319 No task has been processed yet.
2021-04-15T22:06:20.836318 No task has been processed yet.
2021-04-15T22:06:31.356600 No task has been processed yet.
2021-04-15T22:06:41.760447 No task has been processed yet.
2021-04-15T22:06:52.225511 No task has been processed yet.
2021-04-15T22:07:02.628868 No task has been processed yet.
2021-04-15T22:07:12.903598 No task has been processed yet.
2021-04-15T22:07:23.276791 No task has been processed yet.
2021-04-15T22:07:33.653752 No task has been processed yet.
2021-04-15T22:07:44.095648 No task has been processed yet.
2021-04-15T22:07:54.472934 No task has been processed yet.
2021-04-15T22:08:04.849691 No task has been processed yet.
2021-04-15T22:08:15.227536 No task has been processed yet.
2021-04-15T22:08:15.281126 Job failed. Please check the sys logs for error details.
2021-04-15T22:08:15.314135 The overviewer on 10.0.0.4 stopped.
2021-04-15T22:08:30.602258 Start to generate the report.
2021-04-15T22:08:37.358300 Saved the report to logs/sys/job_report/processed_mini-batches.csv.
```

And this is from master_role:

```
No mini batch has been completed. Consider a succeeded mini batch or failed mini batch reached the max tries as completed.

The run() function in the entry script had timeout for 236 times. Please check logs/user/error/* and logs/sys/error/* to see if some errors have occurred. Otherwise, check logs/sys/node/*/processNNN.mini-batch.csv to confirm the tasks timeout, if run method expected to take longer time, try to increase run invocation timeout  and try again. Also check logs/sys/perf/* to see if the node is overloaded.

See logs/readme.txt for description of the log layout.
Refer to https://aka.ms/prstsg for more troubleshooting guidance. . Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/###/azureml/####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/master_role_process.py", line 61, in run
    loop.run_until_complete(self.master_role.start())
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/####/wd/prs_prod/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/master_role.py", line 216, in start
    await self.process_tasks()
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/master_role.py", line 359, in process_tasks
    self.summarize()
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/master_role.py", line 253, in summarize
    summary.summarize(self.progress_monitor.error_msg)
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/#####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/progress_summary.py", line 164, in summarize
    self.check_cause(processed_items, failed_items, progress_error_msg)
  File "/mnt/batch/tasks/shared/LS_root/jobs/####/azureml/####/wd/prs_prod/lib/python3.8/site-packages/azureml_sys/parallel_run/progress_summary.py", line 131, in check_cause
    raise EntryScriptException(
azureml_common.parallel_run.exception.EntryScriptException: No progress update in 270 seconds. No progress update in this check. Wait 272 seconds since last update. Remain 0 seconds to progress timeout. 0 among 276 mini batches processed. Please check logs/user/error/* and logs/sys/error/* to see if some errors have occurred.

No mini batch has been completed. Consider a succeeded mini batch or failed mini batch reached the max tries as completed.

The run() function in the entry script had timeout for 236 times. Please check logs/user/error/* and logs/sys/error/* to see if some errors have occurred. Otherwise, check logs/sys/node/*/processNNN.mini-batch.csv to confirm the tasks timeout, if run method expected to take longer time, try to increase run invocation timeout  and try again. Also check logs/sys/perf/* to see if the node is overloaded.
```

So there are no successful tasks.

**Comment by MelissaKR** [comment] 2021-04-15 23:43
I just tried with run_invocation_timeout=120, but still get the same errors.

**Comment by psavdekar** [comment] 2021-04-15 23:53
We are looking into the issue. At this point I think there are 2 issues: run method time out, making task visible again. We will get back to you after doing more investigation.
For run method timeout you may want to add some log in run method which may help us understand where run method is getting stuck. This link has example on logging from entry script.
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-debug-parallel-run-step#how-do-i-log-from-my-user-script-from-a-remote-context

**Comment by MelissaKR** [comment] 2021-04-16 01:19
@psavdekar, I really appreciate it, as I really need to get this part done soon.

**Comment by benchwang** [comment] 2021-04-16 05:03
Hi @MelissaKR,
The set task visible exception (KeyError) is a new bug. We have fixed it in [the PR](https://msdata.visualstudio.com/Vienna/_git/AzureMlCli/pullrequest/556003).
When a task is timeout, we will make it visible and remove from `picked_tasks`. Set visible task tried to make it visible again and resulted the error. We have deployed the PR, so this noisy error should go away. It's a noise and should not impact the result.

Would you check logs/user/ for logs printed in your entry script to see where it stopped in your entry script? If it timeout before hitting your entry script, it may be caused by taking more time to load your data. For either case, increasing the timeout like below would help:

```
    run_config = ParallelRunConfig(
        ...
        run_invocation_timeout=30, # Change to a larger value, I guess yours is 30 seconds as I saw  "duration": 90.nnn.
    )
```

**Comment by MelissaKR** [comment] 2021-04-16 14:19
Hi @benchwang, thank you so much for taking care of this bug. I added logging as suggested by @psavdekar and increased runtime to 180 s. The logs show batch files being processed by run(), however this time the script started processing them, but it was SUPER slow! Like it took it 10 minutes to process 1 file! 

I'll go ahead and give it another try. So is the bug fixed only in the latest version of azure ml packages? I mean, do I need to use a specific version? Currently, I'm using 1.25.0. 

Thanks a ton!

**Comment by MelissaKR** [comment] 2021-04-16 15:43
I just successfully completed the run! Thank you all for your help! :)

**Comment by benchwang** [comment] 2021-04-16 15:46
@MelissaKR, I went through #1405. The problem is that processing 1 file took less than 30 seconds before, but now took 10 minutes.

Do you have log to tell if the delay is inside or outside of the run( ) method? If you don't have, you may add log at the begin and end of run( ) method.
If inside of the method, then you can compare the current sys/node/[node id]/_installed_packages.txt with the one in prior normal run. It has the installed packages for user environment. As you didn't change image, packages should be the cause.
If outside of the method, please share _installed_packages.txt and we should be able to repro.

The latest azureml-core and azureml-dataset-runtime are 1.26.0. I am not aware of any performance issue in recent versions. A try of the latest may help.

For base image, if you don't specify one, it will use `azureml.core.environment.DEFAULT_CPU_IMAGE` with the value `mcr.microsoft.com/azureml/intelmpi2018.3-ubuntu16.04:20210301.v1`. It's different from yours (mcr.microsoft.com/azureml/base:openmpi3.1.2-ubuntu18.04). I don't know the history about the default image. This is a difference I found.

The bug we fixed is on service side and will be downloaded automatically, so you don't need to change any thing for it. The downloaded one is in python 3.8. Hope this answer your question that you saw 3.8 error while you're using 3.7 in your user env.

**Comment by benchwang** [comment] 2021-04-16 15:46
Is the time back to expected?

**Comment by MelissaKR** [comment] 2021-04-16 16:15
Thank you so much for your detailed response, @benchwang ! The time is back to normal, although after adding the logs, I realized there were CPU shortage issues in some of the processes in the previous runs which likely caused runtime problems. I reduced process_count_per_node which fixed that problem. Although, what confuses me is that I was using a dataset that was 8 times bigger with the same script before and I never ran into memory issues. Don't know what changed since then.

I ended up using version 1.26.0, although I'm using python 3.7, because of version compatibility issues with opencv package.

Here is the _installed_packages.txt for the previous successful run:

```
adal==1.2.6
applicationinsights==0.11.9
azure-common==1.1.27
azure-core==1.12.0
azure-graphrbac==0.61.1
azure-identity==1.4.1
azure-mgmt-authorization==0.61.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-keyvault==2.2.0
azure-mgmt-resource==12.1.0
azure-mgmt-storage==11.2.0
azure-storage-blob==12.8.0
azureml-automl-core==1.25.0
azureml-core==1.25.0
azureml-dataprep==2.11.2
azureml-dataprep-native==30.0.0
azureml-dataprep-rslex==1.9.1
azureml-dataset-runtime==1.25.0
azureml-defaults==1.25.0
azureml-model-management-sdk==1.0.1b6.post1
azureml-pipeline==1.25.0
azureml-pipeline-core==1.25.0
azureml-pipeline-steps==1.25.0
azureml-sdk==1.25.0
azureml-telemetry==1.25.0
azureml-train==1.25.0
azureml-train-automl-client==1.25.0
azureml-train-core==1.25.0
azureml-train-restclients-hyperdrive==1.25.0
backports.tempfile==1.0
backports.weakref==1.0.post1
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cloudpickle==1.6.0
configparser==3.7.4
contextlib2==0.6.0.post1
cryptography==3.4.7
cycler==0.10.0
decorator==4.4.2
dill==0.3.3
distro==1.5.0
docker==4.4.4
dotnetcore2==2.1.20
Flask==1.0.3
fusepy==3.0.1
future==0.18.2
gunicorn==19.9.0
idna==2.10
imageio==2.9.0
importlib-metadata==3.9.1
isodate==0.6.0
itsdangerous==1.1.0
jeepney==0.6.0
Jinja2==2.11.3
jmespath==0.10.0
joblib==1.0.1
json-logging-py==0.2
jsonpickle==2.0.0
kiwisolver==1.3.1
liac-arff==2.5.0
MarkupSafe==1.1.1
matplotlib==3.3.2
msal==1.10.0
msal-extensions==0.2.2
msrest==0.6.21
msrestazure==0.6.4
ndg-httpsclient==0.5.1
networkx==2.5
numpy==1.19.2
oauthlib==3.1.0
opencv-contrib-python==4.1.0.25
pandas==1.1.3
pathspec==0.8.1
Pillow==6.2.1
portalocker==1.7.1
pyarrow==1.0.1
pyasn1==0.4.8
pycparser==2.20
PyJWT==2.0.1
pyOpenSSL==20.0.1
pyparsing==2.4.7
python-dateutil==2.8.1
python-decouple==3.4
pytz==2021.1
PyWavelets==1.1.1
requests==2.25.1
requests-oauthlib==1.3.0
ruamel.yaml==0.17.2
ruamel.yaml.clib==0.2.2
scikit-image==0.18.1
scikit-learn==0.24.1
scipy==1.6.2
SecretStorage==3.3.1
Shapely==1.7.1
six==1.15.0
threadpoolctl==2.1.0
tifffile==2021.3.17
torch==1.7.1
torchvision==0.8.2
typing-extensions==3.7.4.3
urllib3==1.26.4
websocket-client==0.58.0
Werkzeug==1.0.1
zipp==3.4.1
```

And for the most recent successful run:

```
adal==1.2.7
applicationinsights==0.11.9
azure-common==1.1.27
azure-core==1.12.0
azure-graphrbac==0.61.1
azure-identity==1.4.1
azure-mgmt-authorization==0.61.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-keyvault==2.2.0
azure-mgmt-resource==12.1.0
azure-mgmt-storage==11.2.0
azure-storage-blob==12.8.0
azureml-automl-core==1.25.0.post1
azureml-core==1.25.0
azureml-dataprep==2.11.2
azureml-dataprep-native==30.0.0
azureml-dataprep-rslex==1.9.1
azureml-dataset-runtime==1.25.0
azureml-defaults==1.25.0
azureml-model-management-sdk==1.0.1b6.post1
azureml-pipeline==1.25.0
azureml-pipeline-core==1.25.0
azureml-pipeline-steps==1.25.0
azureml-sdk==1.25.0
azureml-telemetry==1.25.0
azureml-train==1.25.0
azureml-train-automl-client==1.25.0
azureml-train-core==1.25.0
azureml-train-restclients-hyperdrive==1.25.0
backports.tempfile==1.0
backports.weakref==1.0.post1
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cloudpickle==1.6.0
configparser==3.7.4
contextlib2==0.6.0.post1
cryptography==3.4.7
cycler==0.10.0
decorator==4.4.2
dill==0.3.3
distro==1.5.0
docker==4.4.4
dotnetcore2==2.1.20
Flask==1.0.3
fusepy==3.0.1
future==0.18.2
gunicorn==19.9.0
idna==2.10
imageio==2.9.0
importlib-metadata==3.10.1
isodate==0.6.0
itsdangerous==1.1.0
jeepney==0.6.0
Jinja2==2.11.3
jmespath==0.10.0
joblib==1.0.1
json-logging-py==0.2
jsonpickle==2.0.0
kiwisolver==1.3.1
liac-arff==2.5.0
MarkupSafe==1.1.1
matplotlib==3.3.2
msal==1.11.0
msal-extensions==0.2.2
msrest==0.6.21
msrestazure==0.6.4
ndg-httpsclient==0.5.1
networkx==2.5.1
numpy==1.19.2
oauthlib==3.1.0
opencv-contrib-python==4.1.0.25
pandas==1.1.3
pathspec==0.8.1
Pillow==6.2.1
portalocker==1.7.1
pyarrow==1.0.1
pyasn1==0.4.8
pycparser==2.20
PyJWT==2.0.1
pyOpenSSL==20.0.1
pyparsing==2.4.7
python-dateutil==2.8.1
python-decouple==3.4
pytz==2021.1
PyWavelets==1.1.1
requests==2.25.1
requests-oauthlib==1.3.0
ruamel.yaml==0.17.4
ruamel.yaml.clib==0.2.2
scikit-image==0.18.1
scikit-learn==0.24.1
scipy==1.6.2
SecretStorage==3.3.1
Shapely==1.7.1
six==1.15.0
threadpoolctl==2.1.0
tifffile==2021.4.8
torch==1.7.1
torchvision==0.8.2
typing-extensions==3.7.4.3
urllib3==1.26.4
websocket-client==0.58.0
Werkzeug==1.0.1
zipp==3.4.1
```
I've also used DEFAULT_CPU_IMAGE for both runs.

**Comment by psavdekar** [comment] 2021-04-16 17:23
@MelissaKR , PRS does add perf stats at regular interval to root cause cpu/memory issues. To root cause slowness I would recommend comparing below between 2 runs (faster & slower)
1. Number of nodes for the job
2. Number of processes/node 
3. Type of compute - same CPU/Memory capacity?
4. Files under logs/perf folder

**Comment by tracychms** [comment] 2021-05-27 15:59
Close the issue as it's been fixed per conversation.

**Closed by tracychms** 2021-05-27 15:59 UTC
Labels: ADO, Inference, product-question
