### ISSUE TITLE
AttributeError: 'TimeSeriesTransformer' object has no attribute 'featurization_config' in energy notebook

### ISSUE THREAD

**Issue by jbraun22** [Azure/MachineLearningNotebooks#1304] opened 2021-01-25 22:06 UTC
Hi Azure Auto ML -

After running the non-lagged experiment in the auto-ML-forecasting-energy-demand notebook, I tried running the cell to retrieve the best model:

best_run, fitted_model = remote_run.get_output()
fitted_model.steps

It threw the attribute error.  Full text is:
 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\Anaconda3\envs\azure_automl\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~\Anaconda3\envs\azure_automl\lib\site-packages\IPython\lib\pretty.py in pretty(self, obj)
    375                 if cls in self.type_pprinters:
    376                     # printer registered in self.type_pprinters
--> 377                     return self.type_pprinters[cls](obj, self, cycle)
    378                 else:
    379                     # deferred printer

~\Anaconda3\envs\azure_automl\lib\site-packages\IPython\lib\pretty.py in inner(obj, p, cycle)
    553                 p.text(',')
    554                 p.breakable()
--> 555             p.pretty(x)
    556         if len(obj) == 1 and type(obj) is tuple:
    557             # Special case for 1-item tuples.

~\Anaconda3\envs\azure_automl\lib\site-packages\IPython\lib\pretty.py in pretty(self, obj)
    375                 if cls in self.type_pprinters:
    376                     # printer registered in self.type_pprinters
--> 377                     return self.type_pprinters[cls](obj, self, cycle)
    378                 else:
    379                     # deferred printer

~\Anaconda3\envs\azure_automl\lib\site-packages\IPython\lib\pretty.py in inner(obj, p, cycle)
    553                 p.text(',')
    554                 p.breakable()
--> 555             p.pretty(x)
    556         if len(obj) == 1 and type(obj) is tuple:
    557             # Special case for 1-item tuples.

~\Anaconda3\envs\azure_automl\lib\site-packages\IPython\lib\pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~\Anaconda3\envs\azure_automl\lib\site-packages\IPython\lib\pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~\Anaconda3\envs\azure_automl\lib\site-packages\sklearn\base.py in __repr__(self, N_CHAR_MAX)
    258             n_max_elements_to_show=N_MAX_ELEMENTS_TO_SHOW)
    259 
--> 260         repr_ = pp.pformat(self)
    261 
    262         # Use bruteforce ellipsis when there are a lot of non-blank characters

~\Anaconda3\envs\azure_automl\lib\pprint.py in pformat(self, object)
    142     def pformat(self, object):
    143         sio = _StringIO()
--> 144         self._format(object, sio, 0, 0, {}, 0)
    145         return sio.getvalue()
    146 

~\Anaconda3\envs\azure_automl\lib\pprint.py in _format(self, object, stream, indent, allowance, context, level)
    159             self._readable = False
    160             return
--> 161         rep = self._repr(object, context, level)
    162         max_width = self._width - indent - allowance
    163         if len(rep) > max_width:

~\Anaconda3\envs\azure_automl\lib\pprint.py in _repr(self, object, context, level)
    391     def _repr(self, object, context, level):
    392         repr, readable, recursive = self.format(object, context.copy(),
--> 393                                                 self._depth, level)
    394         if not readable:
    395             self._readable = False

~\Anaconda3\envs\azure_automl\lib\site-packages\sklearn\utils\_pprint.py in format(self, object, context, maxlevels, level)
    179     def format(self, object, context, maxlevels, level):
    180         return _safe_repr(object, context, maxlevels, level,
--> 181                           changed_only=self._changed_only)
    182 
    183     def _pprint_estimator(self, object, stream, indent, allowance, context,

~\Anaconda3\envs\azure_automl\lib\site-packages\sklearn\utils\_pprint.py in _safe_repr(object, context, maxlevels, level, changed_only)
    423         recursive = False
    424         if changed_only:
--> 425             params = _changed_params(object)
    426         else:
    427             params = object.get_params(deep=False)

~\Anaconda3\envs\azure_automl\lib\site-packages\sklearn\utils\_pprint.py in _changed_params(estimator)
     89     estimator with non-default values."""
     90 
---> 91     params = estimator.get_params(deep=False)
     92     init_func = getattr(estimator.__init__, 'deprecated_original',
     93                         estimator.__init__)

~\Anaconda3\envs\azure_automl\lib\site-packages\sklearn\base.py in get_params(self, deep)
    193         out = dict()
    194         for key in self._get_param_names():
--> 195             value = getattr(self, key)
    196             if deep and hasattr(value, 'get_params'):
    197                 deep_items = value.get_params().items()

AttributeError: 'TimeSeriesTransformer' object has no attribute 'featurization_config'

If I run the python statements one at a time, it is the fitted_model.steps statement that causes the error.

Thanks for your help.

**Comment by nick863** [comment] 2021-02-01 19:31
This exception is caused by the incompatible version of scikit-learn.
Please install the version scikit-learn>=0.19.0,<0.23.0
```
pip install "scikit-learn>=0.19.0,<0.23.0"
```
After installing a compatible version of scikit learn the notebook kernel needs to be restarted.
To avoid training model again, please add another cell before the model retrieving:

```
from azureml.core import Experiment, Workspace
from azureml.train.automl.runtime.run import AutoMLRun

ws = Workspace.from_config()
# Choose an experiment name.
# Please make sure that the experiment name is the same as in notebook. 
experiment_name = 'automl-forecasting-energydemand'
# Copy the run ID shown after submission of the remote run.
run_id = 'Please_insert_the_run_id_from_the_notebook_here'

experiment = Experiment(ws, experiment_name)
remote_run = AutoMLRun(experiment, run_id)
```

Now the model can be retrieved:
```
best_run, fitted_model = remote_run.get_output()
fitted_model.steps
```

**Comment by CESARDELATORRE** [comment] 2021-02-02 01:07
Closing the issue since it was solved with a solution by nick863:
Update to version scikit-learn>=0.19.0,<0.23.0

Please, re-open if needed.

**Closed by CESARDELATORRE** 2021-02-02 01:07 UTC
Labels: Auto ML, product-issue

**Comment by jbraun22** [comment] 2021-02-02 22:29
@nick863 That worked!  Thank you
