### ISSUE TITLE
the notebook https://aka.ms/pl-style-trans has no MpiStep example.

### ISSUE THREAD

**Issue by damochiz** [Azure/MachineLearningNotebooks#783] opened 2020-02-10 02:42 UTC
This page shows "For an example of using MpiStep, see the notebook https://aka.ms/pl-style-trans" but the linked page doesn't look like an example of using MpiStep. Please fix the linked URL or page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00db76ef-5f7c-4685-b4ee-535fa9f9016a
* Version Independent ID: 30d18264-1388-61d7-085e-ae49c0db7805
* Content: [azureml.pipeline.steps.mpi_step.MpiStep class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.mpi_step.mpistep?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.mpi_step.MpiStep.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-pipeline-steps/azureml.pipeline.steps.mpi_step.MpiStep.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by YutongTie-MSFT** [comment] 2020-03-11 17:26
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by RohitMungi-MSFT** [comment] 2020-04-15 12:11
#922 is duplicate of this issue

**Closed** 2020-06-17 16:58 UTC
Labels: Pipelines, assigned-to-author, doc-bug, machine-learning/svc, triaged
