### ISSUE TITLE
generate Dataset profile fails

### ISSUE THREAD

**Issue by swanderz** [Azure/MachineLearningNotebooks#657] opened 2019-11-14 17:03 UTC
I'm trying to make a dataset profile and it is failing. @jenren @rastala @MayMSFT 
## `70_driver_log.txt`
```python
Starting the daemon thread to refresh tokens in background for process with pid = 381
Entering Run History Context Manager.
Start running action, id = 7d5caf9c-b336-4a91-8a93-d791c3142892, for dataset, id = 5cdc3fd7-f57e-46ff-bf24-e463dcbd30fc


The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 300.0 seconds
2 items cleaning up...
Cleanup took 0.0033681392669677734 seconds
Traceback (most recent call last):
  File "run_dataset_action.py", line 45, in <module>
    _DatasetClient._execute_dataset_action(workspace, dataset_id, action_id, dataflow_json)
  File "/azureml-envs/azureml_ca4b89a0721c57884e8acd0380bc8d20/lib/python3.6/site-packages/azureml/data/_dataset_client.py", line 2027, in _execute_dataset_action
    result_artifacts.append(_DatasetClient._upload_preview(workspace, action, dflow))
  File "/azureml-envs/azureml_ca4b89a0721c57884e8acd0380bc8d20/lib/python3.6/site-packages/azureml/data/_dataset_client.py", line 2113, in _upload_preview
    preview_flow.run_local()
  File "/azureml-envs/azureml_ca4b89a0721c57884e8acd0380bc8d20/lib/python3.6/site-packages/azureml/dataprep/api/_loggerfactory.py", line 131, in wrapper
    return func(*args, **kwargs)
  File "/azureml-envs/azureml_ca4b89a0721c57884e8acd0380bc8d20/lib/python3.6/site-packages/azureml/dataprep/api/dataflow.py", line 630, in run_local
    anonymous_activity=Dataflow._dataflow_to_anonymous_activity_data(self)
  File "/azureml-envs/azureml_ca4b89a0721c57884e8acd0380bc8d20/lib/python3.6/site-packages/azureml/dataprep/api/_aml_helper.py", line 38, in wrapper
    return send_message_func(op_code, message, cancellation_token)
  File "/azureml-envs/azureml_ca4b89a0721c57884e8acd0380bc8d20/lib/python3.6/site-packages/azureml/dataprep/api/engineapi/api.py", line 94, in execute_anonymous_activity
    response = self._message_channel.send_message('Engine.ExecuteActivity', message_args, cancellation_token)
  File "/azureml-envs/azureml_ca4b89a0721c57884e8acd0380bc8d20/lib/python3.6/site-packages/azureml/dataprep/api/engineapi/engine.py", line 119, in send_message
    raise_engine_error(response['error'])
  File "/azureml-envs/azureml_ca4b89a0721c57884e8acd0380bc8d20/lib/python3.6/site-packages/azureml/dataprep/api/errorhandlers.py", line 22, in raise_engine_error
    raise ExecutionError(error_response)
azureml.dataprep.api.errorhandlers.ExecutionError: Could not execute the specified transform.|session_id=l_9bd4b9a7-95e1-44c1-a7c3-e40b7ccd0150


```

**Comment by jenren** [comment] 2019-12-11 19:23
We followed up offline a while ago to resolve this issue. @swanderz let us know if this occurs again! Marking this as closed.

**Closed** 2019-12-11 22:58 UTC

**Comment by rhooper1967** [comment] 2020-08-07 14:43
Hello, I have been experiencing the same issue when following DP100 training lab 7B. Can you please indicate if the problem is intermittent or there is an underlying issue with the compute resource or other that I need to address? 

Many thanks for your help

**Comment by MayMSFT** [comment] 2020-08-07 18:37
hi @rhooper1967 

How are you generating the profile? through studio UI?
