### ISSUE TITLE
Custom datastores are not mounted in AML compute instances

### ISSUE THREAD

**Issue by jarandaf** [Azure/MachineLearningNotebooks#1202] opened 2020-10-23 15:06 UTC
When I use a non-default datastore and a `PipelineData` object as output of a `PythonScriptStep` (used for model training) I get the following error when trying to save model predictions:

`FileNotFoundError: [Errno 2] No such file or directory: '/mnt/batch/tasks/shared/LS_root/jobs/***/azureml/01a92f9b-91a6-4675-a995-0bc63e196071/mounts/foo/azureml/01a92f9b-91a6-4675-a995-0bc63e196071/predictions'`

where `foo` is an existing and attached datastore and `***` is the ML workspace.

This does not happen when I use the default datastore.

**Comment by MayMSFT** [comment] 2020-10-23 23:04
Hi @jarandaf  

Can you share how you defined the pipelinedata object?

**Comment by jarandaf** [comment] 2020-10-24 06:20
`predictions_output = PipelineData('predictions', datastore=blob_datastore).as_dataset().register(predictions_name)`

**Comment by MayMSFT** [comment] 2020-10-27 00:29
Hi @jarandaf

I cant reproduce the issue. Here is the code sample i used:
![image](https://user-images.githubusercontent.com/47834041/97242301-c0b98a00-17b0-11eb-8784-23c2e858975b.png)

my sdk version: 1.16.0

**Comment by meyetman** [comment] 2020-11-05 18:39
Closing this issue, but let use know if you are still experiencing this problem. #please-close

**Closed by meyetman** 2020-11-05 18:39 UTC
Labels: Data4ML, product-issue
