### ISSUE TITLE
SnapshotException 403

### ISSUE THREAD

**Issue by ryotatomioka** [Azure/MachineLearningNotebooks#1175] opened 2020-10-05 09:02 UTC
Hi,

I have encountered SnapshotException with status code 403. It turns out that I have a read permission but not write permission for the subscription I was trying to submit my job to. It would be better if the error message was more informative.

This is the current error message
```
raise SnapshotException(get_http_exception_response_string(response))
azureml.exceptions._azureml_exception.SnapshotException: SnapshotException:
        Message: {
    "status_code": 403,
    "url": "..."
}
        InnerException None
        ErrorResponse
{
    "error": {
        "message": "{\n    \"status_code\": 403,\n    \"url\": \"...\"\n}"
    }
}
```

I think a better error message would be
```
Please make sure that you have write permission to subscription XYZ.
```

It might also be a good idea to document here what the typical causes for different status codes are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c023d0b-94c0-8b80-3a43-e0d5beb2eefb
* Version Independent ID: 22714d0e-0f49-7264-5329-7c7b3e163d2d
* Content: [azureml.exceptions.SnapshotException class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.exceptions.snapshotexception?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.exceptions.SnapshotException.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.exceptions.SnapshotException.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by lostmygithubaccount** [comment] 2020-10-05 18:43
duplicate of #1176 - closing in favor of that issue

**Closed by lostmygithubaccount** 2020-10-05 18:43 UTC
Labels: duplicate
